<?php
/**
 * @category    CleverSoft
 * @package     CleverSocialLogin
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php
$helper = $this->helper('CleverSoft\CleverSocialLogin\Helper\Data');
if($helper->moduleEnabled() && $helper->isFakeMail()) : ?>
	<div class="pslogin-fake-email-message" data-mage-init='{"pslogin":{}}'>
		<div class="content">
			<div class="close-message">&#10005;</div>
			<p>
				<?php echo __('Your account needs to be updated. The email address in your profile is invalid. Please indicate your valid email address by going to the <a href="%1">Account edit page</a>', $block->getUrl('customer/account/edit')); ?>
			</p>
		</div>
	</div>
<?php endif; ?>