<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Language switcher template
 */
$_matoHelper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
?>
<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <?php if( $_matoHelper->getCfg('header/img_flag') == 1): ?>
                <img src="<?php echo $_matoHelper->getMediaUrl('wysiwyg/cleversoft/flag/') . strtolower($block->escapeHtml($block->getStoreName()))?>.png" alt="<?php echo $block->escapeHtml($block->getStoreName()) ?>"/>
                <?php endif; ?>
                <span><?php echo $block->escapeHtml($block->getStoreName()) ?></span>
            </strong>
        </div>
        <ul class="switcher-dropdown" >
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                    <?php if( $_matoHelper->getCfg('header/img_flag') == 1): ?>
                        <img src="<?php echo $_matoHelper->getMediaUrl('wysiwyg/cleversoft/flag/') . strtolower($block->escapeHtml($_lang->getName()))?>.png" alt="<?php echo $_lang->getName()?>"/>
                    <?php endif; ?>
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                            <?php echo $block->escapeHtml($_lang->getName()) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>