<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="newsletter-cs">
    <h4 class="title"><span><?php echo __('Newsletter') ?></span></h4>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?php /* @escapeNotVerified */
              echo $block->getFormActionUrl() ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field newsletter">
                    <input name="email" type="email" id="newsletter" class="form-control" placeholder="<?php /* @escapeNotVerified */
                    echo __('Email address') ?>"
                           data-validate="{required:true, 'validate-email':true}"/>
            </div>
            <div class="actions">
                <button class="btn-novetty action subscribe "
                         type="submit">
                 <?php /* @escapeNotVerified */
                        echo __('Sign Up') ?>
                </button>
            </div>
        </form>
    </div>
</div>

              
           