<?php
/**
 * @category    CleverSoft
 * @package     CleverLayeredNavigation
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php
/** @var $block \CleverSoft\CleverLayeredNavigation\Block\Adminhtml\Page\Edit\Tab\Selection\Value */
?>
<?php if ($block->getFrontendInput() === 'select') :?>
    <select name="<?php /* @escapeNotVerified */ echo $block->getInputName()?>" class="select admin__control-select">
        <?php foreach($block->getAttributeOptions() as $_option): ?>
            <option
                value="<?php /* @escapeNotVerified */ echo $_option['value'];?>"
                <?php echo ($_option['value'] === $block->getEavAttributeValue() ? 'selected' : '')?>
                >
                <?php /* @escapeNotVerified */ echo $_option['label'];?>
            </option>
        <?php endforeach;?>
    </select>

<?php elseif ($block->getFrontendInput() === 'multiselect') : ?>
    <select name="<?php /* @escapeNotVerified */ echo $block->getInputName()?>[]" class="select multiselect admin__control-multiselect cleversoft-shopby-selection-multiselect" multiple="multiple">
        <?php foreach($block->getAttributeOptions() as $_option): ?>
            <option
                value="<?php /* @escapeNotVerified */ echo $_option['value'];?>"
                <?php echo (is_array($block->getEavAttributeValue()) && in_array($_option['value'], $block->getEavAttributeValue()) ? 'selected' : '')?>
            >
                <?php /* @escapeNotVerified */ echo $_option['label'];?>
            </option>
        <?php endforeach;?>
    </select>
<?php else: ?>
    <input
        value="<?php /* @escapeNotVerified */ echo $block->getEavAttributeValue()?>"
        name="<?php /* @escapeNotVerified */ echo $block->getInputName()?>"
        class="input-text" type="text"
    />
<?php endif;?>