<?php
/**
 * @category    CleverSoft
 * @package     CleverBuilder
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php
$image_url = $block->getViewFileUrl('CleverSoft_CleverBuilder::images/transparent.gif');
?>
<script>
    requirejs(['jquery', 'jQueryLibMin'],function ($) {
        //container is a selector
        window.lazyloadfunction = function() {
            if ($(".clazyload").length > 0) {
                $(".clazyload").lazyload({
                    data_attribute: "src",
                    placeholder: '<?php echo $image_url;?>',
                    threshold: '0',
                    failure_limit : 10,
                    load:
                        function(){
                            $(this).waitForImages({
                                finished: function() {
                                },
                                each: function() {
                                    $(this).addClass('clazyloading');
                                },
                                waitForAll: true
                            }).done(function() {
                                $(this).removeClass('clazyloading');
                                $(this).addClass('clazyloaded');
                            })
                        }
                });
            }
        };
        $(function () {
            lazyloadfunction();
            $(document).bind('ajaxComplete', function(){
                lazyloadfunction();
            });
        });
    });
</script>