<?php
$_matoHelper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$_helperCookie = $this->helper('CleverSoft\CleverCookieLaw\Helper\Data');
?>
<div class="contact">
    <p class="page-sub-title"><?php /* @escapeNotVerified */ echo __('Call us when you need the best services') ?></p>
    <?php echo $_matoHelper->getCfg('contact_google_map/html_google_map'); ?>
    <div class="contact_content">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h3>
                        <?php /* @escapeNotVerified */ echo __('Get In Touch') ?>
                    </h3>
                    <form class="contact-form"
                          action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
                          id="contact-form"
                          method="post"
                          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
                          data-mage-init='{"validation":{}}'>
                          <p><input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/></p>
                                <p><input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/></p>
                                <p><input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" /></p>
                                <p><textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea></p>
                       <?php echo $block->getChildHtml('form.additional.info'); ?>
                        <?php if($_helperCookie->getSystemConfig('integration', 'contact')):?>
                            <input style="float:left;margin: 8px 10px 0 0;width:inherit;height:inherit" data-validate="{required:true}" type="checkbox" name="integration[contact]"><?php echo $_helperCookie->getSystemConfig('integration', 'contact_text')?><br>
                            <div id="contact_integration_error" class="message info empty" style="display:none">
                                <div><?php echo $_helperCookie->getSystemConfig('integration', 'contact_error')?></div>
                            </div>
                        <?php endif;?>
                        <div class="form-actions">
                            <input type="hidden" name="hideit" id="hideit" value="" />
                            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="btn-novetty btn-raised primary">
                                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <?php include ($block->getTemplateFile('Magento_Contact::map.phtml')) ?>
</div>
<?php if($_helperCookie->getSystemConfig('integration', 'contact')):?>
    <script>
        require(['jquery'], function($){ 
            $(document).ready(function() {
                $("#contact-form").submit(function() {
                    $('#contact_integration_error').show();
                });
            });
        });
    </script>
<?php endif;?>

