<?php
/**
 * @category    CleverSoft
 * @package     CleverSocialLogin
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author      ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php
/**
 * Create account form template
 * @var $block \Magento\Customer\Block\Form\Register
 */
$_helper = $this->helper('CleverSoft\CleverCookieLaw\Helper\Data');
?>
<?php echo $block->getChildHtml('form_fields_before')?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.register.extra')?>
    <form class="social-form account form-create-account" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="social-form-validate" enctype="multipart/form-data" autocomplete="off">
        <?php /* @noEscape */ echo $block->getBlockHtml('formkey'); ?>
        <div class=" create info">
            <fieldset>
                <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Personal Information') ?></span></legend>
                <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
                <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
                <div class="field field-name-firstname required">
                    <label class="label">
                        <span><?php /* @escapeNotVerified */ echo __('First Name')?></span>
                    </label>
                    <div class="control">
                        <input type="text" id="social-firstname" name="firstname" value="" title="<?php /* @escapeNotVerified */ echo __('First Name')?>" placeholder="<?php /* @escapeNotVerified */ echo __('First Name')?>" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
                    </div>
                </div>
                <div class="field field-name-lastname required">
                    <label class="label">
                        <span><?php /* @escapeNotVerified */ echo __('Last Name')?></span>
                    </label>
                    <div class="control">
                        <input type="text" id="social-lastname" name="lastname" value="" title="<?php /* @escapeNotVerified */ echo __('Last Name')?>" placeholder="<?php /* @escapeNotVerified */ echo __('Last Name')?>" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
                    </div>
                </div>

                <div class="field required">
                    <div class="control">
                        <input type="email" name="email" id="social_email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <?php if ($block->isNewsletterEnabled()): ?>
                    <div class="field choice newsletter">
                        <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?>" value="1" id="social_is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                        <label class="label"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?></span></label>
                    </div>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $block->getChildHtml('customer.form.register.newsletter')?>
                <?php endif ?>

                <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                <?php endif ?>

                <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
                <?php endif ?>

                <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
                <?php if ($_gender->isEnabled()): ?>
                    <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                <?php endif ?>
            </fieldset>
        </div>
        <?php if ($block->getShowAddressFields()): ?>
            <div class=" address">
                <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address Information') ?></span></legend>
                <input type="hidden" name="create_address" value="1" />
                <div class="field company">
                    <div class="control">
                        <input type="text" name="company" id="social-company" value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                    </div>
                </div>
                <div class="field telephone">
                    <div class="control">
                        <input type="text" name="telephone" id="social-telephone" value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
                    </div>
                </div>

                <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

                <div class="field street required">
                    <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
                    <div class="control">
                        <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="social-street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                        <div class="nested">
                            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                            <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                <div class="field additional">
                                    <div class="control">
                                        <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Address') ?>" id="social-street_<?php /* @escapeNotVerified */ echo $_i ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                    </div>
                                </div>
                            <?php endfor; ?>
                        </div>
                    </div>
                </div>

                <div class="field required">
                    <div class="control">
                        <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="social-city">
                    </div>
                </div>

                <div class="field region required">
                    <label for="region_id" class="label"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                    <div class="control">
                        <select id="social_region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" style="display:none;">
                            <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                        </select>
                        <input type="text" id="social-region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Password *') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                    </div>
                </div>

                <div class="field zip required">
                    <div class="control">
                        <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="social-zip" placeholder="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                    </div>
                </div>

                <div class="field country required">
                    <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                    <div class="control">
                        <?php echo $block->getCountryHtmlSelect() ?>
                    </div>
                </div>
                <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                <?php if ($addressAttributes): ?>
                    <?php $addressAttributes->setEntityType('customer_address'); ?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                    <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                    <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
                <?php endif;?>
                <input type="hidden" name="default_billing" value="1">
                <input type="hidden" name="default_shipping" value="1">
            </div>

        <?php endif; ?>
        <div class=" create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
            <fieldset>
                <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Sign-in Information') ?></span></legend>

                <div class="field password required">
                    <div class="control">
                        <input type="password" name="password" id="social-password" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" class="input-text" placeholder="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}" autocomplete="off">
                    </div>
                </div>
                <div class="field confirmation required">
                    <div class="control">
                        <input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="social-password-confirmation" class="input-text" placeholder="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" data-validate="{required:true, equalTo:'#social-password'}" autocomplete="off">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <?php echo $block->getChildHtml('create.captcha'); ?>
            </fieldset>
        </div>
        <?php if($_helper->getSystemConfig('integration', 'register')):?>
            <input style="float:left;margin: 7px 10px 0 0;width:15px;height:inherit" data-validate="{required:true}" type="checkbox" name="integration[socialregister]"><?php echo $_helper->getSystemConfig('integration', 'register_text')?><br>
            <div id="social_register_popup_integration_error" class="message info empty" style="display:none">
                <div><?php echo $_helper->getSystemConfig('integration', 'register_error')?></div>
            </div>
        <?php endif;?>
        <div class="actions">
            <a class="action create" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></a>
            <button type="submit" class="btn action submit" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></button>

        </div>

    </form>
    <script>
        require([
            'jquery',
            'mage/mage'
        ], function($){

            var dataForm = $('.form-create-account');
            var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

            dataForm.mage('validation', {
                <?php if ($_dob->isEnabled()): ?>
                errorPlacement: function(error, element) {
                    if (element.prop('id').search('full') !== -1) {
                        var dobElement = $(element).parents('.customer-dob'),
                            errorClass = error.prop('class');
                        error.insertAfter(element.parent());
                        dobElement.find('.validate-custom').addClass(errorClass)
                            .after('<div class="' + errorClass + '"></div>');
                    }
                    else {
                        error.insertAfter(element);
                    }
                },
                ignore: ':hidden:not(' + ignore + ')'
                <?php else: ?>
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                <?php endif ?>
            }).find('input:text').attr('autocomplete', 'off');

        });
    </script>
<?php if ($block->getShowAddressFields()): ?>
    <script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#social_region_id",
                "regionInputId": "#social-region",
                "postcodeId": "#social-zip",
                "form": "#social-form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>
<?php if($_helper->getSystemConfig('integration', 'register')):?>
    <script>
        require(['jquery'], function($){
            $(document).ready(function() {
                $("#social-form-validate").submit(function() {
                    if($('input[name="integration[socialregister]"]').is(":checked")) {
                        $('#social_register_popup_integration_error').hide();
                    } else {
                        $('#social_register_popup_integration_error').show();
                    }
                });
            });
        });
    </script>
<?php endif;?>