<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
    <h4 class="block-title">
        <?php echo __('Latest News') ?>
    </h4>
    <div class="block-content">
        <?php foreach ($_postCollection as $_post) { ?>

            <?php
            $_postName = $block->escapeHtml($_post->getTitle(), null, true);
            ?>
            <div class="item">
                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                    <div class="item-img pull-left">
                        <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                    </div>
                <?php } ?>
                <div class="item-info pull-right">
                    <h5><a class="post-item-link"
                       href="<?php echo $_post->getPostUrl() ?>">
                        <?php echo $block->escapeHtml($_post->getTitle()) ?>
                    </a></h5>
                    <p class="item-publishdate">
                    <?php echo $_post->getPublishDate('F d, Y') ?>
                    </p>
                </div>
            </div>

        <?php } ?>
    </div>
</div>
<?php } ?>
