<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
	$id = uniqid('clever-full-width-');
	$_matoHelper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
	$rtl_language = $_matoHelper->getCfg('responsive/rtl_language');
    $imageWidth = (int)$block->getData('image_width') ? (int)$block->getData('image_width') : 500;
    $imageHeight = (int)$block->getData('image_height') ? (int)$block->getData('image_height') : 300;
$keepRatio = (int)$block->getData('keep_ratio') ? (int)$block->getData('keep_ratio') : 0;
?>
<?php if ($_postCollection->count()) { ?>
    <div id="<?php echo $id; ?>" class="post-list-wrapper blog-widget-recent blog_widget">
    <div class="text-center"> <h3 class="title"><span><?php echo $block->escapeHtml($block->getTitle()) ?></span></h3></div>
    <div class="post-list clearfix container">
        <div class="row">
            <ul>
            <?php foreach ($_postCollection as $_post) { ?>
                <?php
                    $_postUrl = $_post->getPostUrl();
                    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
                ?>
                <li class="post-holder post-holder-<?php echo $_post->getId() ?> col-md-4">
                    <div class="post-header">

                        <?php if ($featuredImage = $_post->getData('featured_img')) { ?>
                            <div class="post-ftimg-hld">
                                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                    <img src="<?php echo $this->helper('Magefan\Blog\Helper\Image')->init($featuredImage)->resize($imageWidth, ($keepRatio ? null : $imageHeight)); ?>" alt="<?php echo $_postName ?>" />
                                </a>
                                <div class="post-info clear">
                                    <div class="item post-posed-date">
                                        <?php echo $_post->getPublishDate('M d, Y') ?>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="post-text">

                            <div class="post-title clearfix">
                                    <a class="post-item-link"
                                       href="<?php echo $_postUrl ?>">
                                        <?php echo $_postName; ?>
                                    </a>
                            </div>
                            <div class="post-content">
                                <div class="post-description clearfix">
                                    <div class="clearfix">
                                        <?php echo substr($block->getShorContent($_post),0,150).'...'; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php } ?>
            </ul>
        </div>
    </div>
    </div>
<?php } ?>