<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<div class="swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId() ?>"
     data-mage-init='{"cleverSwatchRenderer":{
                    "selectorProduct":".product-item-details",
                    "onlySwatches":"true",
                    "classes": {
                            "attributeClass": "swatch-attribute",
                            "attributeInput": "swatch-input",
                            "optionClass": "swatch-option"
                    },
                    "equalHeightConfig":<?php echo $this->helper('CleverSoft\CleverTheme\Helper\Data')->getCfg('category_grid/equal_height') ?  'true' : 'false' ?>,
                    "enableControlLabel":"false",
                    "numberToShow":"<?php /* @escapeNotVerified */ echo $block->getNumberSwatchesPerProduct(); ?>",
                    "jsonConfig":<?php /* @escapeNotVerified */ echo $block->getJsonConfig(); ?>,
                    "jsonSwatchConfig":<?php /* @escapeNotVerified */ echo $block->getJsonSwatchConfig(); ?>,
                    "mediaCallback":"<?php /* @escapeNotVerified */ echo $block->getMediaCallback(); ?>"
                }}'
    ></div>