<?php
$helper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$storeCode = $this->getRequest()->getParam('store');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
if ($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getId()) {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getFooterStyle());
} else {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',0)->getFirstItem()->getFooterStyle());
}
if($settings){
    
    $data = isset($settings->footer) ? $settings->footer : '{}';
}
?>
<!-- Modal content -->
<div class="footerbuilder-modal-content">
    <div class="footerbuilder-modal-footer">
        <span class="footerbuilder-modal-close">&times;</span>
    </div>
    <div class="footerbuilder-modal-body">
        <strong>Copyright</strong>
        <div class="modal-inner" id="footer_desktop_footer-copyright" style="display: none">
            <ul>
                <li id="customize-control-copyright-icon_align" class="customize-control customize-control-copyright-icon_align"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Align items</span>
                    </label>
                    <select name="settings[footer][_customize-input-copyright-icon_align]">
                        <option value="0" <?= isset($data->{'_customize-input-copyright-icon_align'}) && $data->{'_customize-input-copyright-icon_align'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="left" <?= isset($data->{'_customize-input-copyright-icon_align'}) && $data->{'_customize-input-copyright-icon_align'} == 'left' ? 'selected' : '' ?>>
                            Left
                        </option>
                        </option>
                        <option value="right" <?= isset($data->{'_customize-input-copyright-icon_align'}) && $data->{'_customize-input-copyright-icon_align'} == 'right' ? 'selected' : '' ?>>
                            Right
                        </option>
                        <option value="center" <?= isset($data->{'_customize-input-copyright-icon_align'}) && $data->{'_customize-input-copyright-icon_align'} == 'center' ? 'selected' : '' ?>>
                            Center
                        </option>
                    </select>
                </li>
                <li id="customize-control-copyright-icon_size" class="customize-control customize-control-copyright-icon_size"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Icon Size (px)</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[footer][_customize-input-copyright-icon_size]" value="<?= isset($data->{'_customize-input-copyright-icon_size'}) && $data->{'_customize-input-copyright-icon_size'} ? $data->{'_customize-input-copyright-icon_size'} : '' ?>">
                </li>
                <li>
                    <label class="customizer-text">
                        <span class="customize-control-title">Copyright Text</span>
                        <small class="customize-control-description">Arbitrary HTML code or shortcode. Avaiable tags: {current_year}</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <textarea name="settings[footer][_customize-textarea-copyright]" id="_customize-textarea-copyright" rows="5" cols="75"
                              class="input-text"><?php echo isset($data->{'_customize-textarea-copyright'}) ? $data->{'_customize-textarea-copyright'} : ''; ?></textarea>
                </li>
            </ul>

        </div>
        <div class="modal-inner" id="footer_mobile_footer-copyright" style="display:none;">
            <ul>
                <li id="customize-control-copyright-icon-mobile_align" class="customize-control customize-control-copyright-icon-mobile_align"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Align items</span>
                    </label>
                    <select name="settings[footer][_customize-input-copyright-icon-mobile_align]">
                        <option value="0" <?= isset($data->{'_customize-input-copyright-icon-mobile_align'}) && $data->{'_customize-input-copyright-icon-mobile_align'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="left" <?= isset($data->{'_customize-input-copyright-icon-mobile_align'}) && $data->{'_customize-input-copyright-icon-mobile_align'} == 'left' ? 'selected' : '' ?>>
                            Left
                        </option>
                        </option>
                        <option value="right" <?= isset($data->{'_customize-input-copyright-icon-mobile_align'}) && $data->{'_customize-input-copyright-icon-mobile_align'} == 'right' ? 'selected' : '' ?>>
                            Right
                        </option>
                        <option value="center" <?= isset($data->{'_customize-input-copyright-icon-mobile_align'}) && $data->{'_customize-input-copyright-icon-mobile_align'} == 'center' ? 'selected' : '' ?>>
                            Center
                        </option>
                    </select>
                </li>
                <li id="customize-control-copyright-icon-mobile_size" class="customize-control customize-control-copyright-icon-mobile_size"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Icon Size (px)</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[footer][_customize-input-copyright-icon-mobile_size]" value="<?= isset($data->{'_customize-input-copyright-icon-mobile_size'}) && $data->{'_customize-input-copyright-icon-mobile_size'} ? $data->{'_customize-input-copyright-icon-mobile_size'} : '' ?>">
                </li>

                <li>
                    <label class="customizer-text">
                        <span class="customize-control-title">Copyright Text</span>
                        <small class="customize-control-description">Arbitrary HTML code or shortcode. Avaiable tags: {current_year}</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <textarea name="settings[footer][_customize-textarea-copyright-mobile]" id="_customize-textarea-copyright-mobile" rows="5" cols="75"
                              class="input-text"><?php echo isset($data->{'_customize-textarea-copyright-mobile'}) ? $data->{'_customize-textarea-copyright-mobile'} : ''; ?></textarea>
                </li>

        </div>
    </div>
</div>