<?php
$helper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$storeCode = $this->getRequest()->getParam('store');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
if ($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getId()) {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getFooterStyle());
} else {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',0)->getFirstItem()->getFooterStyle());
}
if($settings){
    $data = isset($settings->footer) ? $settings->footer : '{}';
}
?>
<!-- Modal content -->
<div class="footerbuilder-modal-content">
    <div class="footerbuilder-modal-footer">
        <span class="footerbuilder-modal-close">&times;</span>
    </div>
    <div class="footerbuilder-modal-body">
        <strong>Copyright</strong>
        <div class="modal-inner" id="desktop_footer-copyright" style="display: none">
            <textarea name="settings[footer][_customize-textarea-copyright]" id="_customize-textarea-copyright" rows="5" cols="75"
                      class="input-text"><?php echo isset($data->{'_customize-textarea-copyright'}) ? $data->{'_customize-textarea-copyright'} : ''; ?></textarea>

            <script>
                require([
                    'jquery',
                    'mage/adminhtml/wysiwyg/tiny_mce/setup'
                ], function (jQuery) {

                    var config = '',
                        editor;

                    jQuery.extend(config, {
                        settings: {
                            theme_advanced_buttons1: 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                            'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                            theme_advanced_buttons2: null,
                            theme_advanced_buttons3: null,
                            theme_advanced_buttons4: null,
                            theme_advanced_statusbar_location: null
                        },
                        files_browser_window_url: false
                    });

                    editor = new tinyMceWysiwygSetup(
                        '_customize-textarea-copyright',
                        config
                    );

                    editor.turnOn();

                    jQuery('#_customize-textarea-copyright')
                        .addClass('wysiwyg-editor')
                        .data(
                            'wysiwygEditor',
                            editor
                        );
                });
            </script>
        </div>
        <div class="modal-inner" id="mobile_footer-copyright" style="display:none;">
            <textarea name="settings[footer][_customize-textarea-copyright-mobile]" id="_customize-textarea-copyright-mobile" rows="5" cols="75"
                      class="input-text"><?php echo isset($data->{'_customize-textarea-copyright-mobile'}) ? $data->{'_customize-textarea-copyright-mobile'} : ''; ?></textarea>

            <script>
                require([
                    'jquery',
                    'mage/adminhtml/wysiwyg/tiny_mce/setup'
                ], function (jQuery) {

                    var config = '',
                        editor;

                    jQuery.extend(config, {
                        settings: {
                            theme_advanced_buttons1: 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                            'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                            theme_advanced_buttons2: null,
                            theme_advanced_buttons3: null,
                            theme_advanced_buttons4: null,
                            theme_advanced_statusbar_location: null
                        },
                        files_browser_window_url: false
                    });

                    editor = new tinyMceWysiwygSetup(
                        '_customize-textarea-copyright-mobile',
                        config
                    );

                    editor.turnOn();

                    jQuery('#_customize-textarea-copyright-mobile')
                        .addClass('wysiwyg-editor')
                        .data(
                            'wysiwygEditor',
                            editor
                        );
                });
            </script>
        </div>
    </div>
</div>