<?php
$helper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$storeCode = $this->getRequest()->getParam('store');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$staticBlocks = $objectManager->create('\Magento\Cms\Model\Block')->getCollection()->addFieldToFilter('use_in_headerbuilder',1);
if ($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getId()) {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getFooterStyle());
} else {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',0)->getFirstItem()->getFooterStyle());
}
if($settings){
    $data = isset($settings->footer) ? $settings->footer : '{}';
}
?>
<!-- Modal content -->
<div class="footerbuilder-modal-content">
    <div class="footerbuilder-modal-footer">
        <span class="footerbuilder-modal-close">&times;</span>
    </div>
    <div class="footerbuilder-modal-body">
        <strong>Footer Widget 1</strong>
        <div class="modal-inner" id="footer_desktop_footer-widget-1" style="display: none">
            <ul>
                <li>
                    <select name="settings[footer][_customize-select-footer-widget-1]">
                        <option value="">Select Static Block</option>
                        <?php foreach ($staticBlocks as $block):?>
                            <option value="<?php echo $block->getData('identifier');?>" <?php echo isset($data->{'_customize-select-footer-widget-1'}) && $data->{'_customize-select-footer-widget-1'} == $block->getData('identifier') ? 'selected' : ''?>><?php echo $block->getData('title');?></option>
                        <?php endforeach;?>
                    </select>
                </li>
                <li id="customize-control-footer-widget-1_margin" class="customize-control customize-control-footer-widget-1-margin"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Margin</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[footer][_customize-input-footer-widget-1_margin]" value="<?= isset($data->{'_customize-input-footer-widget-1_margin'}) && $data->{'_customize-input-footer-widget-1_margin'} ? $data->{'_customize-input-footer-widget-1_margin'} : '' ?>">
                </li>
                <li id="customize-control-footer_footer-widget-1_merge_item" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Merge Item</span>
                        <small class="customize-control-description">If you choose to merge this item, the alignment setting will inherit from the item you are merging.</small>
                    </label>
                    <select name="settings[footer][_customize_footer_footer-widget-1_merge_item]">
                        <option value="0" <?= isset($data->{'_customize_footer_footer-widget-1_merge_item'}) && $data->{'_customize_footer_footer-widget-1_merge_item'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="prev" <?= isset($data->{'_customize_footer_footer-widget-1_merge_item'}) && $data->{'_customize_footer_footer-widget-1_merge_item'} == 'prev' ? 'selected' : '' ?>>
                            Merge with previous item
                        </option>
                        <option value="next" <?= isset($data->{'_customize_footer_footer-widget-1_merge_item'}) && $data->{'_customize_footer_footer-widget-1_merge_item'} == 'next' ? 'selected' : '' ?>>
                            Merge with next item
                        </option>
                    </select>
                </li>
            </ul>
        </div>
        <div class="modal-inner" id="footer_mobile_footer-widget-1" class="tabcontent" style="display:none;">
            <ul>
                <li>
                    <select name="settings[footer][_customize-select-footer-widget-1-mobile]">
                        <?php foreach ($staticBlocks as $block):?>
                            <option value="<?php echo $block->getData('identifier');?>" <?php echo isset($data->{'_customize-select-footer-widget-1-mobile'}) && $data->{'_customize-select-footer-widget-1-mobile'} == $block->getData('identifier') ? 'selected' : ''?>><?php echo $block->getData('title');?></option>
                        <?php endforeach;?>
                    </select>
                </li>
                <li id="customize-control-footer-widget-1-mobile_margin" class="customize-control customize-control-footer-widget-1-margin"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Margin</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[footer][_customize-input-footer-widget-1-mobile_margin]" value="<?= isset($data->{'_customize-input-footer-widget-1-mobile_margin'}) && $data->{'_customize-input-footer-widget-1-mobile_margin'} ? $data->{'_customize-input-footer-widget-1-mobile_margin'} : '' ?>">
                </li>
                <li id="customize-control-footer_footer-widget-1_merge_item_mobile" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Merge Item</span>
                        <small class="customize-control-description">If you choose to merge this item, the alignment setting will inherit from the item you are merging.</small>
                    </label>
                    <select name="settings[footer][_customize_footer_footer-widget-1_merge_item_mobile]">
                        <option value="0" <?= isset($data->{'_customize_footer_footer-widget-1_merge_item_mobile'}) && $data->{'_customize_footer_footer-widget-1_merge_item_mobile'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="prev" <?= isset($data->{'_customize_footer_footer-widget-1_merge_item_mobile'}) && $data->{'_customize_footer_footer-widget-1_merge_item_mobile'} == 'prev' ? 'selected' : '' ?>>
                            Merge with previous item
                        </option>
                        <option value="next" <?= isset($data->{'_customize_footer_footer-widget-1_merge_item_mobile'}) && $data->{'_customize_footer_footer-widget-1_merge_item_mobile'} == 'next' ? 'selected' : '' ?>>
                            Merge with next item
                        </option>
                    </select>
                </li>
            </ul>
        </div>
    </div>
</div>