<?php
$helper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$storeCode = $this->getRequest()->getParam('store');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
if ($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getId()) {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getHeaderStyle());
} else {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',0)->getFirstItem()->getHeaderStyle());
}
if($settings){
    $data = isset($settings->footer) ? $settings->footer : '{}';
}
?>
<!-- Modal content -->
<div class="headerbuilder-modal-content">
    <div class="headerbuilder-modal-header">
        <span class="headerbuilder-modal-close">&times;</span>
    </div>
    <div class="headerbuilder-modal-body">
        <strong>Language</strong>
        <div class="modal-inner" id="desktop_footer_language" style="display: none">
            <ul class="customize-pane-child accordion-section-content accordion-section control-section control-section-kirki-default open"
                id="sub-accordion-section-header_search">
                <li id="customize-control-footer_language_margin" class="customize-control customize-control-footer_language-margin"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Margin</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[footer][_customize-input-footer_language_margin]" value="<?= isset($data->{'_customize-input-footer_language_margin'}) && $data->{'_customize-input-footer_language_margin'} ? $data->{'_customize-input-footer_language_margin'} : '' ?>">
                </li>
                <li id="customize-control-footer_language_align" class="customize-control customize-control-footer_language_align"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Align items</span>
                    </label>
                    <select name="settings[footer][_customize-input-footer_language_align]">
                        <option value="0" <?= isset($data->{'_customize-input-footer_language_align'}) && $data->{'_customize-input-footer_language_align'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="left" <?= isset($data->{'_customize-input-footer_language_align'}) && $data->{'_customize-input-footer_language_align'} == 'left' ? 'selected' : '' ?>>
                            Left
                        </option>
                        </option>
                        <option value="right" <?= isset($data->{'_customize-input-footer_language_align'}) && $data->{'_customize-input-footer_language_align'} == 'right' ? 'selected' : '' ?>>
                            Right
                        </option>
                    </select>
                </li>
                <li id="customize-control-header_footer_language_merge_item" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Merge Item</span>
                        <small class="customize-control-description">If you choose to merge this item, the alignment setting will inherit from the item you are merging.</small>
                    </label>
                    <select name="settings[footer][_customize_header_footer_language_merge_item]">
                        <option value="0" <?= isset($data->{'_customize_header_footer_language_merge_item'}) && $data->{'_customize_header_footer_language_merge_item'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="prev" <?= isset($data->{'_customize_header_footer_language_merge_item'}) && $data->{'_customize_header_footer_language_merge_item'} == 'prev' ? 'selected' : '' ?>>
                            Merge with previous item
                        </option>
                        <option value="next" <?= isset($data->{'_customize_header_footer_language_merge_item'}) && $data->{'_customize_header_footer_language_merge_item'} == 'next' ? 'selected' : '' ?>>
                            Merge with next item
                        </option>
                    </select>
                </li>
            </ul>
        </div>
        <div class="modal-inner" id="mobile_footer_language" style="display: none">
            <ul class="customize-pane-child accordion-section-content accordion-section control-section control-section-kirki-default open"
                id="sub-accordion-section-header_search">
                <li id="customize-control-mobile_footer_language_margin" class="customize-control customize-control-footer_language-margin"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Margin</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[footer][_customize-input-mobile_footer_language_margin]" value="<?= isset($data->{'_customize-input-mobile_footer_language_margin'}) && $data->{'_customize-input-mobile_footer_language_margin'} ? $data->{'_customize-input-mobile_footer_language_margin'} : '' ?>">
                </li>
                <li id="customize-control-footer_language_align-mobile" class="customize-control customize-control-footer_language_align-mobile"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Align items</span>
                    </label>
                    <select name="settings[footer][_customize-input-footer_language_align-mobile]">
                        <option value="0" <?= isset($data->{'_customize-input-footer_language_align-mobile'}) && $data->{'_customize-input-footer_language_align-mobile'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="left" <?= isset($data->{'_customize-input-footer_language_align-mobile'}) && $data->{'_customize-input-footer_language_align-mobile'} == 'left' ? 'selected' : '' ?>>
                            Left
                        </option>
                        </option>
                        <option value="right" <?= isset($data->{'_customize-input-footer_language_align-mobile'}) && $data->{'_customize-input-footer_language_align-mobile'} == 'right' ? 'selected' : '' ?>>
                            Right
                        </option>
                    </select>
                </li>
                <li id="customize-control-header_footer_language_merge_item_mobile" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Merge Item</span>
                        <small class="customize-control-description">If you choose to merge this item, the alignment setting will inherit from the item you are merging.</small>
                    </label>
                    <select name="settings[footer][_customize_header_footer_language_merge_item_mobile]">
                        <option value="0" <?= isset($data->{'_customize_header_footer_language_merge_item_mobile'}) && $data->{'_customize_header_footer_language_merge_item_mobile'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="prev" <?= isset($data->{'_customize_header_footer_language_merge_item_mobile'}) && $data->{'_customize_header_footer_language_merge_item_mobile'} == 'prev' ? 'selected' : '' ?>>
                            Merge with previous item
                        </option>
                        <option value="next" <?= isset($data->{'_customize_header_footer_language_merge_item_mobile'}) && $data->{'_customize_header_footer_language_merge_item_mobile'} == 'next' ? 'selected' : '' ?>>
                            Merge with next item
                        </option>
                    </select>
                </li>
            </ul>
        </div>
    </div>
</div>