<?php
$helper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$storeCode = $this->getRequest()->getParam('store');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
if ($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getId()) {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getFooterStyle());
} else {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',0)->getFirstItem()->getFooterStyle());
}
if($settings){
    
    $data = isset($settings->footer) ? $settings->footer : '{}';
}
?>
<!-- Modal content -->
<div class="footerbuilder-modal-content">
    <div class="footerbuilder-modal-footer">
        <span class="footerbuilder-modal-close">&times;</span>
    </div>
    <div class="footerbuilder-modal-body">
        <strong>HTML 2</strong>
        <div class="modal-inner" id="footer_desktop_footer-html-2" style="display: none">
            <ul>
                <li id="customize-control-footer-html-2_margin" class="customize-control customize-control-footer-html-2-margin"
                        style="display: list-item;">
                        <label class="customizer-text">
                            <span class="customize-control-title">Margin</span>
                            <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                            <div class="customize-control-notifications-container" style="display: none;">
                                <ul></ul>
                            </div>
                        </label>
                        <input type="text" name="settings[footer][_customize-input-footer-html-2_margin]" value="<?= isset($data->{'_customize-input-footer-html-2_margin'}) && $data->{'_customize-input-footer-html-2_margin'} ? $data->{'_customize-input-footer-html-2_margin'} : '' ?>">
                    </li>
                <li id="customize-control-footer_footer-html-2_merge_item" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Merge Item</span>
                        <small class="customize-control-description">If you choose to merge this item, the alignment setting will inherit from the item you are merging.</small>
                    </label>
                    <select name="settings[footer][_customize_footer_footer-html-2_merge_item]">
                        <option value="0" <?= isset($data->{'_customize_footer_footer-html-2_merge_item'}) && $data->{'_customize_footer_footer-html-2_merge_item'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="prev" <?= isset($data->{'_customize_footer_footer-html-2_merge_item'}) && $data->{'_customize_footer_footer-html-2_merge_item'} == 'prev' ? 'selected' : '' ?>>
                            Merge with previous item
                        </option>
                        <option value="next" <?= isset($data->{'_customize_footer_footer-html-2_merge_item'}) && $data->{'_customize_footer_footer-html-2_merge_item'} == 'next' ? 'selected' : '' ?>>
                            Merge with next item
                        </option>
                    </select>
                </li>
                <li id="customize-control-footer_footer-html-2_merge_item" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Content</span>
                    </label>
                    <textarea name="settings[footer][_customize-textarea-footer-html-2]" id="_customize-textarea-footer-html-2" rows="5" cols="75"
                              class="input-text"><?php echo isset($data->{'_customize-textarea-footer-html-2'}) ? $data->{'_customize-textarea-footer-html-2'} : ''; ?></textarea>

                    <script>
                        require([
                            'jquery',
                            'mage/adminhtml/wysiwyg/tiny_mce/setup'
                        ], function (jQuery) {

                            var config = '',
                                editor;

                            jQuery.extend(config, {
                                settings: {
                                    theme_advanced_buttons1: 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                    'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                                    theme_advanced_buttons2: null,
                                    theme_advanced_buttons3: null,
                                    theme_advanced_buttons4: null,
                                    theme_advanced_statusbar_location: null
                                },
                                files_browser_window_url: false
                            });

                            editor = new tinyMceWysiwygSetup(
                                '_customize-textarea-footer-html-2',
                                config
                            );

                            editor.turnOn();

                            jQuery('#_customize-textarea-footer-html-2')
                                .addClass('wysiwyg-editor')
                                .data(
                                    'wysiwygEditor',
                                    editor
                                );
                        });
                    </script>
                </li>
            </ul>
        </div>
        <div class="modal-inner" id="footer_mobile_footer-html-2" style="display:none;">
            <ul>
                <li id="customize-control-footer-html-2-mobile_margin" class="customize-control customize-control-footer-html-2-margin"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Margin</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[footer][_customize-input-footer-html-2-mobile_margin]" value="<?= isset($data->{'_customize-input-footer-html-2-mobile_margin'}) && $data->{'_customize-input-footer-html-2-mobile_margin'} ? $data->{'_customize-input-footer-html-2-mobile_margin'} : '' ?>">
                </li>
                <li id="customize-control-footer_footer-html-2_merge_item_mobile" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Merge Item</span>
                        <small class="customize-control-description">If you choose to merge this item, the alignment setting will inherit from the item you are merging.</small>
                    </label>
                    <select name="settings[footer][_customize_footer_footer-html-2_merge_item_mobile]">
                        <option value="0" <?= isset($data->{'_customize_footer_footer-html-2_merge_item_mobile'}) && $data->{'_customize_footer_footer-html-2_merge_item_mobile'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="prev" <?= isset($data->{'_customize_footer_footer-html-2_merge_item_mobile'}) && $data->{'_customize_footer_footer-html-2_merge_item_mobile'} == 'prev' ? 'selected' : '' ?>>
                            Merge with previous item
                        </option>
                        <option value="next" <?= isset($data->{'_customize_footer_footer-html-2_merge_item_mobile'}) && $data->{'_customize_footer_footer-html-2_merge_item_mobile'} == 'next' ? 'selected' : '' ?>>
                            Merge with next item
                        </option>
                    </select>
                </li>
                <li id="customize-control-footer_footer-html-2_merge_item_mobile" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Content</span>
                    </label>  
                    <textarea name="settings[footer][_customize-textarea-footer-html-2-mobile]" id="_customize-textarea-footer-html-2-mobile" rows="5" cols="75"
                              class="input-text"><?php echo isset($data->{'_customize-textarea-footer-html-2-mobile'}) ? $data->{'_customize-textarea-footer-html-2-mobile'} : ''; ?></textarea>

                    <script>
                        require([
                            'jquery',
                            'mage/adminhtml/wysiwyg/tiny_mce/setup'
                        ], function (jQuery) {

                            var config = '',
                                editor;

                            jQuery.extend(config, {
                                settings: {
                                    theme_advanced_buttons1: 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                    'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                                    theme_advanced_buttons2: null,
                                    theme_advanced_buttons3: null,
                                    theme_advanced_buttons4: null,
                                    theme_advanced_statusbar_location: null
                                },
                                files_browser_window_url: false
                            });

                            editor = new tinyMceWysiwygSetup(
                                '_customize-textarea-footer-html-2-mobile',
                                config
                            );

                            editor.turnOn();

                            jQuery('#_customize-textarea-footer-html-2-mobile')
                                .addClass('wysiwyg-editor')
                                .data(
                                    'wysiwygEditor',
                                    editor
                                );
                        });
                    </script>
                </li>
            </ul>
        </div>
    </div>
</div>