<?php
$helper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$storeCode = $this->getRequest()->getParam('store');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
if ($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getId()) {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getHeaderStyle());
} else {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',0)->getFirstItem()->getHeaderStyle());
}
if($settings){
    $data = isset($settings->header) ? $settings->header : '{}';
}

?>
<!-- Modal content -->
<div class="headerbuilder-modal-content">
    <div class="headerbuilder-modal-header">
        <span class="headerbuilder-modal-close">&times;</span>
    </div>
    <div class="headerbuilder-modal-body">
        <strong>LOGO</strong>
        <div class="modal-inner" id="header_desktop_logo" style="display: none">
            <ul>
                <li id="customize-control-logo_margin" class="customize-control customize-control-logo-margin"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Margin (px)</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[header][_customize-input-logo_margin]" value="<?= isset($data->{'_customize-input-logo_margin'}) && $data->{'_customize-input-logo_margin'} ? $data->{'_customize-input-logo_margin'} : '' ?>">
                </li>
                <li id="customize-control-header_logo_merge_item" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Merge Item</span>
                        <small class="customize-control-description">If you choose to merge this item, the alignment setting will inherit from the item you are merging.</small>
                    </label>
                    <select name="settings[header][_customize_header_logo_merge_item]">
                        <option value="0" <?= isset($data->{'_customize_header_logo_merge_item'}) && $data->{'_customize_header_logo_merge_item'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="prev" <?= isset($data->{'_customize_header_logo_merge_item'}) && $data->{'_customize_header_logo_merge_item'} == 'prev' ? 'selected' : '' ?>>
                            Merge with previous item
                        </option>
                        <option value="next" <?= isset($data->{'_customize_header_logo_merge_item'}) && $data->{'_customize_header_logo_merge_item'} == 'next' ? 'selected' : '' ?>>
                            Merge with next item
                        </option>
                    </select>
                </li>
                <li id="customize-control-header_logo_position" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Logo Position</span>
                    </label>
                    <select name="settings[header][_customize_header_logo_position]">
                        <option value="0" <?= isset($data->{'_customize_header_logo_position'}) && $data->{'_customize_header_logo_position'} == '0' ? 'selected' : '' ?>>
                            Left
                        </option>
                        <option value="text-center" <?= isset($data->{'_customize_header_logo_position'}) && $data->{'_customize_header_logo_position'} == 'text-center' ? 'selected' : '' ?>>
                            Center
                        </option>
                        <option value="text-right" <?= isset($data->{'_customize_header_logo_position'}) && $data->{'_customize_header_logo_position'} == 'text-right' ? 'selected' : '' ?>>
                            Right
                        </option>
                    </select>
                </li>
                <li id="customize-control-blogdescription" class="customize-control customize-control-text" style="display: list-item;">
                    <label for="_customize-input-blogdescription" class="customize-control-title">Tagline</label>
                    <div class="customize-control-notifications-container" style="display: none;">
                        <ul></ul>
                    </div>
                    <input id="_customize-input-blogdescription" type="text" name="settings[header][_customize_logo_tagline]" value="<?= isset($data->{'_customize_logo_tagline'}) ? $data->{'_customize_logo_tagline'} :''?>" data-customize-setting-link="blogdescription">
                </li>
                <li id="customize-control-site_logo_slogan" class="customize-control customize-control-checkbox" style="display: list-item;">
                    <div class="customize-control-notifications-container" style="display: none;">
                        <ul></ul>
                    </div>
                    <span class="customize-inside-control-row">
                    <input id="_customize-input-site_logo_slogan" type="checkbox" value="1" name="settings[header][_customize-checkbox-logo-slogan]" <?= isset($data->{'_customize-checkbox-logo-slogan'}) ? 'checked' : ''?> data-customize-setting-link="site_logo_slogan">
                    <label for="_customize-input-site_logo_slogan">Display below Logo</label>
                    </span>
                </li>
                <li id="customize-control-site_logo" class="customize-control customize-control-kirki-image" style="display: list-item;">
                    <label>
                    <span class="customize-control-title">
                    Logo image
                    </span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div class="menu-item-field row type__image field__background">
                        <div class="col-xs-4 label"><span></span></div>
                        <div class="col-xs-8">
                            <input name="settings[header][logo][value]" value="<?php echo isset($data->logo->value) && $data->logo->value ? $data->logo->value :''?>" title="" data-ui-id="form-element-content" id="header_desktop_logo_value">
                            <button type="button" class="scalable action-add-image plugin" onclick="MediabrowserUtility.openDialog('<?php echo $this->getUrl('cms/wysiwyg_images/index')?>target_element_id/header_desktop_logo_value/element_name/settings[header][logo][value]')" style=""><span><span><span>Insert Image...</span></span></span></button>
                            <div class="preview-image-outer">
                                <div class="desktop-logo-preview-image-inner">
                                    <?php if(isset($data->logo->value) && $data->logo->value):?>
                                        <?php $imageUrl = $this->getBaseUrl()."/pub/media/".$data->logo->value?>
                                        <img src="<?php echo $imageUrl?>">
                                    <?php else:?>
                                        <img src="<?php echo $this->getBaseUrl()?>pub/static/adminhtml/Magento/backend/en_US/CleverSoft_CleverMegaMenus/images/menu/placeholder.jpg">
                                    <?php endif;?>
                                    
                                    </a>
                                    <button class="content-btn desktop-logo-image-delete"><i class="fa fa-remove"></i></button>
                                </div>
                            </div>
                            <p class="content-note">Allow file types: jpg, jpeg, png, gif</p>
                            
                        </div>
                    </div>
                </li>
                <li id="customize-control-logo_width" class="customize-control customize-control-kirki-slider" style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Logo container width</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                        <div class="wrapper">
                            <input name="settings[header][_customize_header_logo_with]" value="<?= isset($data->{'_customize_header_logo_with'}) ? $data->{'_customize_header_logo_with'} :''?>">
                        </div>
                    </label>
                </li>
                <li id="customize-control-logo_max_width" class="customize-control customize-control-kirki-generic" style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Logo max width (px)</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                        <div class="customize-control-content">
                            <input value="<?= isset($data->{'_customize_header_logo_max_width'}) ? $data->{'_customize_header_logo_max_width'} :''?>" name="settings[header][_customize_header_logo_max_width]" data-customize-setting-link="logo_max_width" element="input" type="text">
                        </div>
                    </label>
                </li>
                <li id="customize-control-logo_border" class="customize-control customize-control-logo_border"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Border Width</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div class="d-flex element-parent">
                        <div class="row">
                            <input placeholder="top" type="text" name="settings[header][_customize-input-logo_border-top]" value="<?= isset($data->{'_customize-input-logo_border-top'}) && $data->{'_customize-input-logo_border-top'} ? $data->{'_customize-input-logo_border-top'} : '' ?>">
                            <input placeholder="right" type="text" name="settings[header][_customize-input-logo_border-right]" value="<?= isset($data->{'_customize-input-logo_border-right'}) && $data->{'_customize-input-logo_border-right'} ? $data->{'_customize-input-logo_border-right'} : '' ?>">
                            <input placeholder="bottom" type="text" name="settings[header][_customize-input-logo_border-bottom]" value="<?= isset($data->{'_customize-input-logo_border-bottom'}) && $data->{'_customize-input-logo_border-bottom'} ? $data->{'_customize-input-logo_border-bottom'} : '' ?>">
                            <input placeholder="left" type="text" name="settings[header][_customize-input-logo_border-left]" value="<?= isset($data->{'_customize-input-logo_border-left'}) && $data->{'_customize-input-logo_border-left'} ? $data->{'_customize-input-logo_border-left'} : '' ?>">
                        </div>
                    </div>
                </li>
                <li id="customize-control-header_logo_style" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Border Style</span>
                    </label>
                    <select name="settings[header][_customize_header_logo_style]">
                        <option value="" <?= isset($data->{'_customize_header_logo_style'}) && $data->{'_customize_header_logo_style'} == '' ? 'selected' : '' ?>>
                            Default
                        </option>
                        <option value="none" <?= isset($data->{'_customize_header_logo_style'}) && $data->{'_customize_header_logo_style'} == 'none' ? 'selected' : '' ?>>
                            None
                        </option>
                        <option value="solid" <?= isset($data->{'_customize_header_logo_style'}) && $data->{'_customize_header_logo_style'} == 'solid' ? 'selected' : '' ?>>
                            Solid
                        </option>
                        <option value="dotted" <?= isset($data->{'_customize_header_logo_style'}) && $data->{'_customize_header_logo_style'} == 'dotted' ? 'selected' : '' ?>>
                            Dotted
                        </option>
                        <option value="dashed" <?= isset($data->{'_customize_header_logo_style'}) && $data->{'_customize_header_logo_style'} == 'dashed' ? 'selected' : '' ?>>
                            Dashed
                        </option>
                        <option value="double" <?= isset($data->{'_customize_header_logo_style'}) && $data->{'_customize_header_logo_style'} == 'double' ? 'selected' : '' ?>>
                            Double
                        </option>
                        <option value="ridge" <?= isset($data->{'_customize_header_logo_style'}) && $data->{'_customize_header_logo_style'} == 'ridge' ? 'selected' : '' ?>>
                            Ridge
                        </option>
                        <option value="inset" <?= isset($data->{'_customize_header_logo_style'}) && $data->{'_customize_header_logo_style'} == 'inset' ? 'selected' : '' ?>>
                            Inset
                        </option>
                        <option value="outset" <?= isset($data->{'_customize_header_logo_style'}) && $data->{'_customize_header_logo_style'} == 'outset' ? 'selected' : '' ?>>
                            Outset
                        </option>
                    </select>
                </li>
                <li id="customize-control-header_logo_border_color" class="customize-control customize-control-kirki-radio-buttonset" style="display: list-item;">
                    <span class="customize-control-title">Border Color</span>
                    <input id="input_header_logo_border_color" name="settings[header][_customize-radio-logo_border_color]" data-ui-id="adminhtml-system-config-form-field-color-0-text-groups-header-fields-link-color-value" value="<?= isset($data->{'_customize-radio-logo_border_color'}) ? $data->{'_customize-radio-logo_border_color'} : ''?>" class="mColorPicker" type="text">
                    <script>
                        require([
                            "CleverSoft_CleverTheme/js/mcolorpicker/mcolorpicker"
                        ],function(){
                            jQuery(document).ready(function(){
                                jQuery("#input_header_logo_border_color").attr("data-hex", true).width("250px").mColorPicker({imageFolder :"<?= $block->getViewFileUrl('CleverSoft_CleverTheme::js/mcolorpicker/images')?>/"});
                            });

                        });
                    </script>
                </li>
                <li id="customize-control-logo_border-radius" class="customize-control customize-control-logo_border-radius"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Border Radius</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div class="d-flex element-parent">
                        <div class="row">
                            <input placeholder="top-left" type="text" name="settings[header][_customize-input-logo_border-top-left-radius]" value="<?= isset($data->{'_customize-input-logo_border-top-left-radius'}) && $data->{'_customize-input-logo_border-top-left-radius'} ? $data->{'_customize-input-logo_border-top-left-radius'} : '' ?>">
                            <input placeholder="top-right" type="text" name="settings[header][_customize-input-logo_border-top-right-radius]" value="<?= isset($data->{'_customize-input-logo_border-top-right-radius'}) && $data->{'_customize-input-logo_border-top-right-radius'} ? $data->{'_customize-input-logo_border-top-right-radius'} : '' ?>">
                            <input placeholder="bottom-right" type="text" name="settings[header][_customize-input-logo_border-bottom-right-radius]" value="<?= isset($data->{'_customize-input-logo_border-bottom-right-radius'}) && $data->{'_customize-input-logo_border-bottom-right-radius'} ? $data->{'_customize-input-logo_border-bottom-right-radius'} : '' ?>">
                            <input placeholder="bottom-left" type="text" name="settings[header][_customize-input-logo_border-bottom-left-radius]" value="<?= isset($data->{'_customize-input-logo_border-bottom-left-radius'}) && $data->{'_customize-input-logo_border-bottom-left-radius'} ? $data->{'_customize-input-logo_border-bottom-left-radius'} : '' ?>">
                        </div>
                    </div>
                </li>
                <li id="customize-control-logo_padding" class="customize-control customize-control-kirki-slider" style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Logo Padding</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                        <div class="wrapper">
                            <input name="settings[header][_customize_header_logo_padding]" value="<?= isset($data->{'_customize_header_logo_padding'}) ? $data->{'_customize_header_logo_padding'} :''?>">
                        </div>
                    </label>
                </li>
            </ul>
        </div>
        <div class="modal-inner" id="header_mobile_logo" style="display:none;">
            <ul>
                <li id="customize-control-mobile_logo_margin" class="customize-control customize-control-logo-margin"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Margin (px)</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[header][_customize-input-mobile_logo_margin]" value="<?= isset($data->{'_customize-input-mobile_logo_margin'}) && $data->{'_customize-input-mobile_logo_margin'} ? $data->{'_customize-input-mobile_logo_margin'} : '' ?>">
                </li>
                <li id="customize-control-header_logo_merge_item_mobile" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Merge Item</span>
                        <small class="customize-control-description">If you choose to merge this item, the alignment setting will inherit from the item you are merging.</small>
                    </label>
                    <select name="settings[header][_customize_header_logo_merge_item_mobile]">
                        <option value="0" <?= isset($data->{'_customize_header_logo_merge_item_mobile'}) && $data->{'_customize_header_logo_merge_item_mobile'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="prev" <?= isset($data->{'_customize_header_logo_merge_item_mobile'}) && $data->{'_customize_header_logo_merge_item_mobile'} == 'prev' ? 'selected' : '' ?>>
                            Merge with previous item
                        </option>
                        <option value="next" <?= isset($data->{'_customize_header_logo_merge_item_mobile'}) && $data->{'_customize_header_logo_merge_item_mobile'} == 'next' ? 'selected' : '' ?>>
                            Merge with next item
                        </option>
                    </select>
                </li>
                <li id="customize-control-header_logo_mobile_position" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Logo Position</span>
                    </label>
                    <select name="settings[header][_customize_header_logo_mobile_position]">
                        <option value="0" <?= isset($data->{'_customize_header_logo_mobile_position'}) && $data->{'_customize_header_logo_mobile_position'} == '0' ? 'selected' : '' ?>>
                            Left
                        </option>
                        <option value="text-center" <?= isset($data->{'_customize_header_logo_mobile_position'}) && $data->{'_customize_header_logo_mobile_position'} == 'text-center' ? 'selected' : '' ?>>
                            Center
                        </option>
                        <option value="text-right" <?= isset($data->{'_customize_header_logo_mobile_position'}) && $data->{'_customize_header_logo_mobile_position'} == 'text-right' ? 'selected' : '' ?>>
                            Right
                        </option>
                    </select>
                </li>
                <li id="customize-control-blogdescription" class="customize-control customize-control-text" style="display: list-item;">
                    <label for="_customize-input-blogdescription" class="customize-control-title">Tagline</label>
                    <div class="customize-control-notifications-container" style="display: none;">
                        <ul></ul>
                    </div>
                    <input id="_customize-input-blogdescription" type="text" name="settings[header][_customize_logo_mobile_tagline]" value="<?= isset($data->{'_customize_logo_mobile_tagline'}) ? $data->{'_customize_logo_mobile_tagline'} :''?>" data-customize-setting-link="blogdescription">
                </li>
                <li id="customize-control-site_logo_mobile_slogan" class="customize-control customize-control-checkbox" style="display: list-item;">
                    <div class="customize-control-notifications-container" style="display: none;">
                        <ul></ul>
                    </div>
                    <span class="customize-inside-control-row">
                        <input id="_customize-input-site_logo_mobile_slogan" type="checkbox" value="1" name="settings[header][_customize-checkbox-logo_mobile-slogan]" <?= isset($data->{'_customize-checkbox-logo_mobile-slogan'}) ? 'checked' : ''?> data-customize-setting-link="site_logo_mobile_slogan">
                        <label for="_customize-input-site_logo_mobile_slogan">Display below Logo</label>
                    </span>
                </li>
                <li id="customize-control-site_logo_mobile" class="customize-control customize-control-kirki-image" style="display: list-item;">
                    <label>
                    <span class="customize-control-title">
                    Logo image
                    </span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div class="menu-item-field row type__image field__background">
                        <div class="col-xs-4 label"><span></span></div>
                        <div class="col-xs-8">
                            <input name="settings[header][logo_mobile][value]" value="<?php echo isset($data->logo_mobile->value) && $data->logo_mobile->value ? $data->logo_mobile->value :''?>" title="" data-ui-id="form-element-content" id="header_mobile_logo_value">
                            <button type="button" class="scalable action-add-image plugin" onclick="MediabrowserUtility.openDialog('<?php echo $this->getUrl('cms/wysiwyg_images/index')?>target_element_id/header_mobile_logo_value/element_name/settings[header][logo_mobile][value]')" style=""><span><span><span>Insert Image...</span></span></span></button>
                            <div class="preview-image-outer">
                                <div class="mobile-logo-preview-image-inner">
                                    <?php if(isset($data->logo_mobile->value) && $data->logo_mobile->value):?>
                                        <?php $imageUrl = $this->getBaseUrl()."/pub/media/".$data->logo_mobile->value?>
                                        <img src="<?php echo $imageUrl?>">
                                    <?php else:?>
                                        <img src="<?php echo $this->getBaseUrl()?>pub/static/adminhtml/Magento/backend/en_US/CleverSoft_CleverMegaMenus/images/menu/placeholder.jpg">
                                    <?php endif;?>
                                    
                                    </a>
                                    <button class="content-btn mobile-logo-image-delete"><i class="fa fa-remove"></i></button>
                                </div>
                            </div>
                            <p class="content-note">Allow file types: jpg, jpeg, png, gif</p>
                            
                        </div>
                    </div>
                </li>
                <li id="customize-control-logo_mobile_width" class="customize-control customize-control-kirki-slider" style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Logo container width</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                        <div class="wrapper">
                            <input name="settings[header][_customize_header_logo_mobile_with]" value="<?= isset($data->{'_customize_header_logo_mobile_with'}) ? $data->{'_customize_header_logo_mobile_with'} :''?>">
                        </div>
                    </label>
                </li>
                <li id="customize-control-logo_mobile_max_width" class="customize-control customize-control-kirki-generic" style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Logo max width (px)</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                        <div class="customize-control-content">
                            <input value="<?= isset($data->{'_customize_header_logo_mobile_max_width'}) ? $data->{'_customize_header_logo_mobile_max_width'} :''?>" name="settings[header][_customize_header_logo_mobile_max_width]" data-customize-setting-link="logo_mobile_max_width" element="input" type="text">
                        </div>
                    </label>
                </li>
                <li id="customize-control-logo-mobile_border" class="customize-control customize-control-logo-mobile_border"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Border Width</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div class="d-flex element-parent">
                        <div class="row">
                            <input placeholder="top" type="text" name="settings[header][_customize-input-logo-mobile_border-top]" value="<?= isset($data->{'_customize-input-logo-mobile_border-top'}) && $data->{'_customize-input-logo-mobile_border-top'} ? $data->{'_customize-input-logo-mobile_border-top'} : '' ?>">
                            <input placeholder="right" type="text" name="settings[header][_customize-input-logo-mobile_border-right]" value="<?= isset($data->{'_customize-input-logo-mobile_border-right'}) && $data->{'_customize-input-logo-mobile_border-right'} ? $data->{'_customize-input-logo-mobile_border-right'} : '' ?>">
                            <input placeholder="bottom" type="text" name="settings[header][_customize-input-logo-mobile_border-bottom]" value="<?= isset($data->{'_customize-input-logo-mobile_border-bottom'}) && $data->{'_customize-input-logo-mobile_border-bottom'} ? $data->{'_customize-input-logo-mobile_border-bottom'} : '' ?>">
                            <input placeholder="left" type="text" name="settings[header][_customize-input-logo-mobile_border-left]" value="<?= isset($data->{'_customize-input-logo-mobile_border-left'}) && $data->{'_customize-input-logo-mobile_border-left'} ? $data->{'_customize-input-logo-mobile_border-left'} : '' ?>">
                        </div>
                    </div>
                </li>
                <li id="customize-control-header_logo-mobile_style" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Border Style</span>
                    </label>
                    <select name="settings[header][_customize_header_logo-mobile_style]">
                        <option value="" <?= isset($data->{'_customize_header_logo-mobile_style'}) && $data->{'_customize_header_logo-mobile_style'} == '' ? 'selected' : '' ?>>
                            Default
                        </option>
                        <option value="none" <?= isset($data->{'_customize_header_logo-mobile_style'}) && $data->{'_customize_header_logo-mobile_style'} == 'none' ? 'selected' : '' ?>>
                            None
                        </option>
                        <option value="solid" <?= isset($data->{'_customize_header_logo-mobile_style'}) && $data->{'_customize_header_logo-mobile_style'} == 'solid' ? 'selected' : '' ?>>
                            Solid
                        </option>
                        <option value="dotted" <?= isset($data->{'_customize_header_logo-mobile_style'}) && $data->{'_customize_header_logo-mobile_style'} == 'dotted' ? 'selected' : '' ?>>
                            Dotted
                        </option>
                        <option value="dashed" <?= isset($data->{'_customize_header_logo-mobile_style'}) && $data->{'_customize_header_logo-mobile_style'} == 'dashed' ? 'selected' : '' ?>>
                            Dashed
                        </option>
                        <option value="double" <?= isset($data->{'_customize_header_logo-mobile_style'}) && $data->{'_customize_header_logo-mobile_style'} == 'double' ? 'selected' : '' ?>>
                            Double
                        </option>
                        <option value="ridge" <?= isset($data->{'_customize_header_logo-mobile_style'}) && $data->{'_customize_header_logo-mobile_style'} == 'ridge' ? 'selected' : '' ?>>
                            Ridge
                        </option>
                        <option value="inset" <?= isset($data->{'_customize_header_logo-mobile_style'}) && $data->{'_customize_header_logo-mobile_style'} == 'inset' ? 'selected' : '' ?>>
                            Inset
                        </option>
                        <option value="outset" <?= isset($data->{'_customize_header_logo-mobile_style'}) && $data->{'_customize_header_logo-mobile_style'} == 'outset' ? 'selected' : '' ?>>
                            Outset
                        </option>
                    </select>
                </li>
                <li id="customize-control-header_logo-mobile_border_color" class="customize-control customize-control-kirki-radio-buttonset" style="display: list-item;">
                    <span class="customize-control-title">Border Color</span>
                    <input id="input_header_logo-mobile_border_color" name="settings[header][_customize-radio-logo-mobile_border_color]" data-ui-id="adminhtml-system-config-form-field-color-0-text-groups-header-fields-link-color-value" value="<?= isset($data->{'_customize-radio-logo-mobile_border_color'}) ? $data->{'_customize-radio-logo-mobile_border_color'} : ''?>" class="mColorPicker" type="text">
                    <script>
                        require([
                            "CleverSoft_CleverTheme/js/mcolorpicker/mcolorpicker"
                        ],function(){
                            jQuery(document).ready(function(){
                                jQuery("#input_header_logo-mobile_border_color").attr("data-hex", true).width("250px").mColorPicker({imageFolder :"<?= $block->getViewFileUrl('CleverSoft_CleverTheme::js/mcolorpicker/images')?>/"});
                            });

                        });
                    </script>
                </li>
                <li id="customize-control-logo-mobile_border-radius" class="customize-control customize-control-logo-mobile_border-radius"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Border Radius</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div class="d-flex element-parent">
                        <div class="row">
                            <input placeholder="top-left" type="text" name="settings[header][_customize-input-logo-mobile_border-top-left-radius]" value="<?= isset($data->{'_customize-input-logo-mobile_border-top-left-radius'}) && $data->{'_customize-input-logo-mobile_border-top-left-radius'} ? $data->{'_customize-input-logo-mobile_border-top-left-radius'} : '' ?>">
                            <input placeholder="top-right" type="text" name="settings[header][_customize-input-logo-mobile_border-top-right-radius]" value="<?= isset($data->{'_customize-input-logo-mobile_border-top-right-radius'}) && $data->{'_customize-input-logo-mobile_border-top-right-radius'} ? $data->{'_customize-input-logo-mobile_border-top-right-radius'} : '' ?>">
                            <input placeholder="bottom-right" type="text" name="settings[header][_customize-input-logo-mobile_border-bottom-right-radius]" value="<?= isset($data->{'_customize-input-logo-mobile_border-bottom-right-radius'}) && $data->{'_customize-input-logo-mobile_border-bottom-right-radius'} ? $data->{'_customize-input-logo-mobile_border-bottom-right-radius'} : '' ?>">
                            <input placeholder="bottom-left" type="text" name="settings[header][_customize-input-logo-mobile_border-bottom-left-radius]" value="<?= isset($data->{'_customize-input-logo-mobile_border-bottom-left-radius'}) && $data->{'_customize-input-logo-mobile_border-bottom-left-radius'} ? $data->{'_customize-input-logo-mobile_border-bottom-left-radius'} : '' ?>">
                        </div>
                    </div>
                </li>
                <li id="customize-control-logo-mobile_padding" class="customize-control customize-control-logo-mobile-padding"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Padding (px)</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[header][_customize-input-logo-mobile_padding]" value="<?= isset($data->{'_customize-input-logo-mobile_padding'}) && $data->{'_customize-input-logo-mobile_padding'} ? $data->{'_customize-input-logo-mobile_padding'} : '' ?>">
                </li>
                <li id="customize-control-logo_mobile_padding" class="customize-control customize-control-kirki-slider" style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Logo Padding</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                        <div class="wrapper">
                            <input name="settings[header][_customize_header_logo_mobile_padding]" value="<?= isset($data->{'_customize_header_logo_mobile_padding'}) ? $data->{'_customize_header_logo_mobile_padding'} :''?>">
                        </div>
                    </label>
                </li>
            </ul>
        </div>
    </div>
</div>
<script>
require(['jquery', 'jquery/ui'], function($){
    $('input[name="settings[header][logo][value]"]').change(function(e){
        var $val = $(this).val();
        if ($val) {
            var $image_url = "<?php echo $this->getBaseUrl()?>/pub/media/"+$val;
            $(".desktop-logo-preview-image-inner img").attr("src",$image_url);
        }
    });
    $('input[name="settings[header][logo_mobile][value]"]').change(function(e){
        var $val = $(this).val();
        if($val) {
            var $image_url = "<?php echo $this->getBaseUrl()?>/pub/media/"+$val;
            $(".mobile-logo-preview-image-inner img").attr("src",$image_url);
        }
    });
    $(".desktop-logo-image-delete").click(function(e) {
       e.preventDefault();
       $('input[name="settings[header][logo][value]"]').val("");
       $(".desktop-logo-preview-image-inner img").attr("src","<?php echo $this->getBaseUrl()?>pub/static/adminhtml/Magento/backend/en_US/CleverSoft_CleverMegaMenus/images/menu/placeholder.jpg");
   });
    $(".mobile-logo-image-delete").click(function(e) {
        e.preventDefault();
        $('input[name="settings[header][logo_mobile][value]"]').val("");
        $(".mobile-logo-preview-image-inner img").attr("src","<?php echo $this->getBaseUrl()?>pub/static/adminhtml/Magento/backend/en_US/CleverSoft_CleverMegaMenus/images/menu/placeholder.jpg");
    });
});
</script>