<?php
$helper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$storeCode = $this->getRequest()->getParam('store');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$listMenus = $objectManager->create('\CleverSoft\CleverMegaMenus\Model\Menuoptions')->toOptionArray();
if ($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getId()) {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getHeaderStyle());
} else {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',0)->getFirstItem()->getHeaderStyle());
}
if($settings){
    $data = isset($settings->header) ? $settings->header : '{}';
}
?>
<!-- Modal content -->
<div class="headerbuilder-modal-content">
    <div class="headerbuilder-modal-header">
        <span class="headerbuilder-modal-close">&times;</span>
    </div>
    <div class="headerbuilder-modal-body">
        <strong>Icon Canvas On Desktop</strong>
        <div class="modal-inner" id="header_desktop_sidebar_icon" style="display: none">
            <ul>
                <li id="customize-control-header_sidebar_icon_position" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Position Canvas Desktop</span>
                    </label>
                    <select name="settings[header][_customize_header_sidebar_icon_content_position]">
                        <option value="desktop-canvas__left" <?= isset($data->{'_customize_header_sidebar_icon_content_position'}) && $data->{'_customize_header_sidebar_icon_content_position'} == 'desktop-canvas__left' ? 'selected' : '' ?>>
                            Slide From Left
                        </option>
                        <option value="desktop-canvas__right" <?= isset($data->{'_customize_header_sidebar_icon_content_position'}) && $data->{'_customize_header_sidebar_icon_content_position'} == 'desktop-canvas__right' ? 'selected' : '' ?>>
                            Slide From Right
                        </option>
                        <option value="full-width" <?= isset($data->{'_customize_header_sidebar_icon_content_position'}) && $data->{'_customize_header_sidebar_icon_content_position'} == 'full-width' ? 'selected' : '' ?>>
                            Full-screen Overlay
                        </option>
                    </select>
                </li>
                <li id="customize-control-sidebar-menu_color" class="customize-control customize-control-builder-radio-image" style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Text mode color</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div id="input_sidebar-menu_color" class="image">
                        <input class="image-select" type="radio" value="" name="settings[header][_customize-radio-sidebar-menu_color]" id="sidebar-menu_colordark" data-customize-setting-link="sidebar-menu_color" <?=isset($data->{'_customize-radio-sidebar-menu_color'}) && $data->{'_customize-radio-sidebar-menu_color'} ? '' : 'checked'?> data-alt="">
                        <label for="sidebar-menu_colordark" class="sidebar-menu_colordark">
                            <img src="<?=$helper->getMediaUrl().'cleversoft/headerbuilder/img/text-dark.svg'?>">
                            <span class="image-clickable"></span>
                        </label>

                        <input class="image-select" type="radio" value="is-text-light" name="settings[header][_customize-radio-sidebar-menu_color]" id="sidebar-menu_colorlight" data-customize-setting-link="sidebar-menu_color" <?=isset($data->{'_customize-radio-sidebar-menu_color'}) && $data->{'_customize-radio-sidebar-menu_color'} == 'is-text-light' ? 'checked' : ''?> data-alt="">
                        <label for="sidebar-menu_colorlight" class="sidebar-menu_colorlight">
                            <img src="<?=$helper->getMediaUrl().'cleversoft/headerbuilder/img/text-light.svg'?>">
                            <span class="image-clickable"></span>
                        </label>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>