<?php
$helper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$storeCode = $this->getRequest()->getParam('store');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
if ($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getId()) {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',$storeCode)->getFirstItem()->getHeaderStyle());
} else {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\Block')->getCollection()->addFieldToFilter('store_id',0)->getFirstItem()->getHeaderStyle());
}
if($settings){
    $data = isset($settings->header) ? $settings->header : '{}';
}
?>
<!-- Modal content -->
<div class="headerbuilder-modal-content">
    <div class="headerbuilder-modal-header">
        <span class="headerbuilder-modal-close">&times;</span>
    </div>
    <div class="headerbuilder-modal-body">
        <strong>Language</strong>
        <div class="modal-inner" id="header_desktop_store_language" style="display: none">
            <ul class="customize-pane-child accordion-section-content accordion-section control-section control-section-kirki-default open"
                id="sub-accordion-section-header_language">
                <li id="customize-control-header_store_language_merge_item" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Merge Item</span>
                        <small class="customize-control-description">If you choose to merge this item, the alignment setting will inherit from the item you are merging.</small>
                    </label>
                    <select name="settings[header][_customize_header_store_language_merge_item]">
                        <option value="0" <?= isset($data->{'_customize_header_store_language_merge_item'}) && $data->{'_customize_header_store_language_merge_item'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="prev" <?= isset($data->{'_customize_header_store_language_merge_item'}) && $data->{'_customize_header_store_language_merge_item'} == 'prev' ? 'selected' : '' ?>>
                            Merge with previous item
                        </option>
                        <option value="next" <?= isset($data->{'_customize_header_store_language_merge_item'}) && $data->{'_customize_header_store_language_merge_item'} == 'next' ? 'selected' : '' ?>>
                            Merge with next item
                        </option>
                    </select>
                </li>
                <li id="customize-control-language_border" class="customize-control customize-control-language_border"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Border Width</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div class="d-flex element-parent">
                        <div class="row">
                            <input placeholder="top" type="text" name="settings[header][_customize-input-language_border-top]" value="<?= isset($data->{'_customize-input-language_border-top'}) && $data->{'_customize-input-language_border-top'} ? $data->{'_customize-input-language_border-top'} : '' ?>">
                            <input placeholder="right" type="text" name="settings[header][_customize-input-language_border-right]" value="<?= isset($data->{'_customize-input-language_border-right'}) && $data->{'_customize-input-language_border-right'} ? $data->{'_customize-input-language_border-right'} : '' ?>">
                            <input placeholder="bottom" type="text" name="settings[header][_customize-input-language_border-bottom]" value="<?= isset($data->{'_customize-input-language_border-bottom'}) && $data->{'_customize-input-language_border-bottom'} ? $data->{'_customize-input-language_border-bottom'} : '' ?>">
                            <input placeholder="left" type="text" name="settings[header][_customize-input-language_border-left]" value="<?= isset($data->{'_customize-input-language_border-left'}) && $data->{'_customize-input-language_border-left'} ? $data->{'_customize-input-language_border-left'} : '' ?>">
                        </div>
                    </div>
                </li>
                <li id="customize-control-header_language_style" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Border Style</span>
                    </label>
                    <select name="settings[header][_customize_header_language_style]">
                        <option value="" <?= isset($data->{'_customize_header_language_style'}) && $data->{'_customize_header_language_style'} == '' ? 'selected' : '' ?>>
                            Default
                        </option>
                        <option value="none" <?= isset($data->{'_customize_header_language_style'}) && $data->{'_customize_header_language_style'} == 'none' ? 'selected' : '' ?>>
                            None
                        </option>
                        <option value="solid" <?= isset($data->{'_customize_header_language_style'}) && $data->{'_customize_header_language_style'} == 'solid' ? 'selected' : '' ?>>
                            Solid
                        </option>
                        <option value="dotted" <?= isset($data->{'_customize_header_language_style'}) && $data->{'_customize_header_language_style'} == 'dotted' ? 'selected' : '' ?>>
                            Dotted
                        </option>
                        <option value="dashed" <?= isset($data->{'_customize_header_language_style'}) && $data->{'_customize_header_language_style'} == 'dashed' ? 'selected' : '' ?>>
                            Dashed
                        </option>
                        <option value="double" <?= isset($data->{'_customize_header_language_style'}) && $data->{'_customize_header_language_style'} == 'double' ? 'selected' : '' ?>>
                            Double
                        </option>
                        <option value="ridge" <?= isset($data->{'_customize_header_language_style'}) && $data->{'_customize_header_language_style'} == 'ridge' ? 'selected' : '' ?>>
                            Ridge
                        </option>
                        <option value="inset" <?= isset($data->{'_customize_header_language_style'}) && $data->{'_customize_header_language_style'} == 'inset' ? 'selected' : '' ?>>
                            Inset
                        </option>
                        <option value="outset" <?= isset($data->{'_customize_header_language_style'}) && $data->{'_customize_header_language_style'} == 'outset' ? 'selected' : '' ?>>
                            Outset
                        </option>
                    </select>
                </li>
                <li id="customize-control-header_language_border_color" class="customize-control customize-control-kirki-radio-buttonset" style="display: list-item;">
                    <span class="customize-control-title">Border Color</span>
                    <input id="input_header_language_border_color" name="settings[header][_customize-radio-language_border_color]" data-ui-id="adminhtml-system-config-form-field-color-0-text-groups-header-fields-link-color-value" value="<?= isset($data->{'_customize-radio-language_border_color'}) ? $data->{'_customize-radio-language_border_color'} : ''?>" class="mColorPicker" type="text">
                    <script>
                        require([
                            "CleverSoft_CleverTheme/js/mcolorpicker/mcolorpicker"
                        ],function(){
                            jQuery(document).ready(function(){
                                jQuery("#input_header_language_border_color").attr("data-hex", true).width("250px").mColorPicker({imageFolder :"<?= $block->getViewFileUrl('CleverSoft_CleverTheme::js/mcolorpicker/images')?>/"});
                            });

                        });
                    </script>
                </li>
                <li id="customize-control-language_border-radius" class="customize-control customize-control-language_border-radius"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Border Radius</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div class="d-flex element-parent">
                        <div class="row">
                            <input placeholder="top-left" type="text" name="settings[header][_customize-input-language_border-top-left-radius]" value="<?= isset($data->{'_customize-input-language_border-top-left-radius'}) && $data->{'_customize-input-language_border-top-left-radius'} ? $data->{'_customize-input-language_border-top-left-radius'} : '' ?>">
                            <input placeholder="top-right" type="text" name="settings[header][_customize-input-language_border-top-right-radius]" value="<?= isset($data->{'_customize-input-language_border-top-right-radius'}) && $data->{'_customize-input-language_border-top-right-radius'} ? $data->{'_customize-input-language_border-top-right-radius'} : '' ?>">
                            <input placeholder="bottom-right" type="text" name="settings[header][_customize-input-language_border-bottom-right-radius]" value="<?= isset($data->{'_customize-input-language_border-bottom-right-radius'}) && $data->{'_customize-input-language_border-bottom-right-radius'} ? $data->{'_customize-input-language_border-bottom-right-radius'} : '' ?>">
                            <input placeholder="bottom-left" type="text" name="settings[header][_customize-input-language_border-bottom-left-radius]" value="<?= isset($data->{'_customize-input-language_border-bottom-left-radius'}) && $data->{'_customize-input-language_border-bottom-left-radius'} ? $data->{'_customize-input-language_border-bottom-left-radius'} : '' ?>">
                        </div>
                    </div>
                </li>
                <li id="customize-control-language_padding" class="customize-control customize-control-language-padding"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Padding (px)</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[header][_customize-input-language_padding]" value="<?= isset($data->{'_customize-input-language_padding'}) && $data->{'_customize-input-language_padding'} ? $data->{'_customize-input-language_padding'} : '' ?>">
                </li>
                <li id="customize-control-language_margin" class="customize-control customize-control-language-margin"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Margin</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[header][_customize-input-language_margin]" value="<?= isset($data->{'_customize-input-language_margin'}) && $data->{'_customize-input-language_margin'} ? $data->{'_customize-input-language_margin'} : '' ?>">
                </li>
                <li id="customize-control-store_language_align" class="customize-control customize-control-store_language_align"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Align items</span>
                    </label>
                    <select name="settings[header][_customize-input-store_language_align]">
                        <option value="0" <?= isset($data->{'_customize-input-store_language_align'}) && $data->{'_customize-input-store_language_align'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="left" <?= isset($data->{'_customize-input-store_language_align'}) && $data->{'_customize-input-store_language_align'} == 'left' ? 'selected' : '' ?>>
                            Left
                        </option>
                        </option>
                        <option value="right" <?= isset($data->{'_customize-input-store_language_align'}) && $data->{'_customize-input-store_language_align'} == 'right' ? 'selected' : '' ?>>
                            Right
                        </option>
                    </select>
                </li>
            </ul>
        </div>
        <div class="modal-inner" id="header_mobile_store_language" style="display: none">
            <ul class="customize-pane-child accordion-section-content accordion-section control-section control-section-kirki-default open"
                id="sub-accordion-section-header_search">
                <li id="customize-control-header_store_language_merge_item_mobile" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Merge Item</span>
                        <small class="customize-control-description">If you choose to merge this item, the alignment setting will inherit from the item you are merging.</small>
                    </label>
                    <select name="settings[header][_customize_header_store_language_merge_item_mobile]">
                        <option value="0" <?= isset($data->{'_customize_header_store_language_merge_item_mobile'}) && $data->{'_customize_header_store_language_merge_item_mobile'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="prev" <?= isset($data->{'_customize_header_store_language_merge_item_mobile'}) && $data->{'_customize_header_store_language_merge_item_mobile'} == 'prev' ? 'selected' : '' ?>>
                            Merge with previous item
                        </option>
                        <option value="next" <?= isset($data->{'_customize_header_store_language_merge_item_mobile'}) && $data->{'_customize_header_store_language_merge_item_mobile'} == 'next' ? 'selected' : '' ?>>
                            Merge with next item
                        </option>
                    </select>
                </li>
                <li id="customize-control-store_language-mobile_border" class="customize-control customize-control-store_language-mobile_border"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Border Width</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div class="d-flex element-parent">
                        <div class="row">
                            <input placeholder="top" type="text" name="settings[header][_customize-input-store_language-mobile_border-top]" value="<?= isset($data->{'_customize-input-store_language-mobile_border-top'}) && $data->{'_customize-input-store_language-mobile_border-top'} ? $data->{'_customize-input-store_language-mobile_border-top'} : '' ?>">
                            <input placeholder="right" type="text" name="settings[header][_customize-input-store_language-mobile_border-right]" value="<?= isset($data->{'_customize-input-store_language-mobile_border-right'}) && $data->{'_customize-input-store_language-mobile_border-right'} ? $data->{'_customize-input-store_language-mobile_border-right'} : '' ?>">
                            <input placeholder="bottom" type="text" name="settings[header][_customize-input-store_language-mobile_border-bottom]" value="<?= isset($data->{'_customize-input-store_language-mobile_border-bottom'}) && $data->{'_customize-input-store_language-mobile_border-bottom'} ? $data->{'_customize-input-store_language-mobile_border-bottom'} : '' ?>">
                            <input placeholder="left" type="text" name="settings[header][_customize-input-store_language-mobile_border-left]" value="<?= isset($data->{'_customize-input-store_language-mobile_border-left'}) && $data->{'_customize-input-store_language-mobile_border-left'} ? $data->{'_customize-input-store_language-mobile_border-left'} : '' ?>">
                        </div>
                    </div>
                </li>
                <li id="customize-control-header_store_language-mobile_style" class="customize-control customize-control-kirki-select"
                    style="display: list-item;">
                    <label>
                        <span class="customize-control-title">Border Style</span>
                    </label>
                    <select name="settings[header][_customize_header_store_language-mobile_style]">
                        <option value="" <?= isset($data->{'_customize_header_store_language-mobile_style'}) && $data->{'_customize_header_store_language-mobile_style'} == '' ? 'selected' : '' ?>>
                            Default
                        </option>
                        <option value="none" <?= isset($data->{'_customize_header_store_language-mobile_style'}) && $data->{'_customize_header_store_language-mobile_style'} == 'none' ? 'selected' : '' ?>>
                            None
                        </option>
                        <option value="solid" <?= isset($data->{'_customize_header_store_language-mobile_style'}) && $data->{'_customize_header_store_language-mobile_style'} == 'solid' ? 'selected' : '' ?>>
                            Solid
                        </option>
                        <option value="dotted" <?= isset($data->{'_customize_header_store_language-mobile_style'}) && $data->{'_customize_header_store_language-mobile_style'} == 'dotted' ? 'selected' : '' ?>>
                            Dotted
                        </option>
                        <option value="dashed" <?= isset($data->{'_customize_header_store_language-mobile_style'}) && $data->{'_customize_header_store_language-mobile_style'} == 'dashed' ? 'selected' : '' ?>>
                            Dashed
                        </option>
                        <option value="double" <?= isset($data->{'_customize_header_store_language-mobile_style'}) && $data->{'_customize_header_store_language-mobile_style'} == 'double' ? 'selected' : '' ?>>
                            Double
                        </option>
                        <option value="ridge" <?= isset($data->{'_customize_header_store_language-mobile_style'}) && $data->{'_customize_header_store_language-mobile_style'} == 'ridge' ? 'selected' : '' ?>>
                            Ridge
                        </option>
                        <option value="inset" <?= isset($data->{'_customize_header_store_language-mobile_style'}) && $data->{'_customize_header_store_language-mobile_style'} == 'inset' ? 'selected' : '' ?>>
                            Inset
                        </option>
                        <option value="outset" <?= isset($data->{'_customize_header_store_language-mobile_style'}) && $data->{'_customize_header_store_language-mobile_style'} == 'outset' ? 'selected' : '' ?>>
                            Outset
                        </option>
                    </select>
                </li>
                <li id="customize-control-header_store_language-mobile_border_color" class="customize-control customize-control-kirki-radio-buttonset" style="display: list-item;">
                    <span class="customize-control-title">Border Color</span>
                    <input id="input_header_store_language-mobile_border_color" name="settings[header][_customize-radio-store_language-mobile_border_color]" data-ui-id="adminhtml-system-config-form-field-color-0-text-groups-header-fields-link-color-value" value="<?= isset($data->{'_customize-radio-store_language-mobile_border_color'}) ? $data->{'_customize-radio-store_language-mobile_border_color'} : ''?>" class="mColorPicker" type="text">
                    <script>
                        require([
                            "CleverSoft_CleverTheme/js/mcolorpicker/mcolorpicker"
                        ],function(){
                            jQuery(document).ready(function(){
                                jQuery("#input_header_store_language-mobile_border_color").attr("data-hex", true).width("250px").mColorPicker({imageFolder :"<?= $block->getViewFileUrl('CleverSoft_CleverTheme::js/mcolorpicker/images')?>/"});
                            });

                        });
                    </script>
                </li>
                <li id="customize-control-store_language-mobile_border-radius" class="customize-control customize-control-store_language-mobile_border-radius"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Border Radius</span>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <div class="d-flex element-parent">
                        <div class="row">
                            <input placeholder="top-left" type="text" name="settings[header][_customize-input-store_language-mobile_border-top-left-radius]" value="<?= isset($data->{'_customize-input-store_language-mobile_border-top-left-radius'}) && $data->{'_customize-input-store_language-mobile_border-top-left-radius'} ? $data->{'_customize-input-store_language-mobile_border-top-left-radius'} : '' ?>">
                            <input placeholder="top-right" type="text" name="settings[header][_customize-input-store_language-mobile_border-top-right-radius]" value="<?= isset($data->{'_customize-input-store_language-mobile_border-top-right-radius'}) && $data->{'_customize-input-store_language-mobile_border-top-right-radius'} ? $data->{'_customize-input-store_language-mobile_border-top-right-radius'} : '' ?>">
                            <input placeholder="bottom-right" type="text" name="settings[header][_customize-input-store_language-mobile_border-bottom-right-radius]" value="<?= isset($data->{'_customize-input-store_language-mobile_border-bottom-right-radius'}) && $data->{'_customize-input-store_language-mobile_border-bottom-right-radius'} ? $data->{'_customize-input-store_language-mobile_border-bottom-right-radius'} : '' ?>">
                            <input placeholder="bottom-left" type="text" name="settings[header][_customize-input-store_language-mobile_border-bottom-left-radius]" value="<?= isset($data->{'_customize-input-store_language-mobile_border-bottom-left-radius'}) && $data->{'_customize-input-store_language-mobile_border-bottom-left-radius'} ? $data->{'_customize-input-store_language-mobile_border-bottom-left-radius'} : '' ?>">
                        </div>
                    </div>
                </li>
                <li id="customize-control-store_language-mobile_padding" class="customize-control customize-control-store_language-mobile-padding"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Padding (px)</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[header][_customize-input-store_language-mobile_padding]" value="<?= isset($data->{'_customize-input-store_language-mobile_padding'}) && $data->{'_customize-input-store_language-mobile_padding'} ? $data->{'_customize-input-store_language-mobile_padding'} : '' ?>">
                </li>
                <li id="customize-control-mobile_language_margin" class="customize-control customize-control-language-margin"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Margin</span>
                        <small class="customize-control-description">Ex: 5px 5px 5px 5px</small>
                        <div class="customize-control-notifications-container" style="display: none;">
                            <ul></ul>
                        </div>
                    </label>
                    <input type="text" name="settings[header][_customize-input-mobile_language_margin]" value="<?= isset($data->{'_customize-input-mobile_language_margin'}) && $data->{'_customize-input-mobile_language_margin'} ? $data->{'_customize-input-mobile_language_margin'} : '' ?>">
                </li>
                <li id="customize-control-store_language_align-mobile" class="customize-control customize-control-store_language_align-mobile"
                    style="display: list-item;">
                    <label class="customizer-text">
                        <span class="customize-control-title">Align items</span>
                    </label>
                    <select name="settings[header][_customize-input-store_language_align-mobile]">
                        <option value="0" <?= isset($data->{'_customize-input-store_language_align-mobile'}) && $data->{'_customize-input-store_language_align-mobile'} == '0' ? 'selected' : '' ?>>
                            No
                        </option>
                        <option value="left" <?= isset($data->{'_customize-input-store_language_align-mobile'}) && $data->{'_customize-input-store_language_align-mobile'} == 'left' ? 'selected' : '' ?>>
                            Left
                        </option>
                        </option>
                        <option value="right" <?= isset($data->{'_customize-input-store_language_align-mobile'}) && $data->{'_customize-input-store_language_align-mobile'} == 'right' ? 'selected' : '' ?>>
                            Right
                        </option>
                    </select>
                </li>
            </ul>
        </div>
    </div>
</div>