<?php
/**
 * @category    CleverSoft
 * @package     CleverMegaMenus
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<script type="text/html" id="sample01-html"/>
<div class="mega-block-banner space-s">
    <a href="#"><img class="img-responsive" src="{{media url='wysiwyg/cleversoft/megamenu/image-placeholder.png'}}" alt="image-placeholder.png" /></a>
</div>
<h3 class="mega-block-title">Collections</h3>
<div class="mega-block-paragraph">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</div>
</script>

<script type="text/html" id="sample02-html">
<div class="mega-block-banner space-s">
<a href="#"><img class="img-responsive" src="{{media url='wysiwyg/cleversoft/megamenu/image-placeholder.png'}}" alt="image-placeholder.png" /></a>
</div>
<h3 class="mega-block-title">Collections</h3>
<ul class="mega-block">
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Jeans</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Shoes</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Shirt</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Bags</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Shopping Cart</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Checkout</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Wishlist</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Order</a></li>
</ul>
</script>

<script type="text/html" id="sample03-html"/>
<h3 class="mega-block-title">Collections</h3>
<div class="mega-block-paragraph">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</div>
</script>

<script type="text/html" id="sample04-html"/>
<h3 class="mega-block-title">Collections</h3>
<ul class="mega-block">
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Jeans</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Shoes</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Shirt</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Bags</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Shopping Cart</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Checkout</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Wishlist</a></li>
<li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Order</a></li>
</ul>
</script>

<script type="text/html" id="sample05-html"/>
<h3 class="mega-block-title">Collections</h3>
<ul class="mega-block">
    <li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Jeans</a></li>
    <li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Shoes</a></li>
    <li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Shirt</a></li>
    <li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Bags</a></li>
    <li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Shopping Cart</a></li>
    <li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Checkout</a></li>
    <li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Wishlist</a></li>
    <li class="clever-mega-menu-item"><a href="{{store direct_url='#'}}">Order</a></li>
</ul>
<div class="mega-block-banner space-s">
    <a href="#"><img class="img-responsive" src="{{media url='wysiwyg/cleversoft/megamenu/image-placeholder.png'}}" alt="image-placeholder.png" /></a>
</div>
</script>

<script type="text/html" id="sample06-html"/>
<h3 class="mega-block-title">Collections</h3>
<div class="mega-block-paragraph">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</div>
<div class="mega-block-banner space-s">
<a href="#"><img class="img-responsive" src="{{media url='wysiwyg/cleversoft/megamenu/image-placeholder.png'}}" alt="image-placeholder.png" /></a>
</div>
</script>