<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <div class="blog_widget block related">
        <div class="block-title title">
            <h3 id="block-relatedposts-heading" class="text-center" role="heading" aria-level="2">
                <?php echo __('You Might Also Like') ?>
            </h3>
        </div>
        <div class="block-content row">
            <?php foreach ($_postCollection as $_post) { ?>

                <?php
                $_postName = $block->escapeHtml($_post->getTitle(), null, true);
                ?>
                <div class="item col-sm-4">
                    <div class="post-header">
                        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                            <div class="post-ftimg-hld">
                                <a class="post-item-link"
                                   href="<?php echo $_post->getPostUrl() ?>">
                                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                                </a>
                                <div class="post-info clear"><div class="item post-posed-date"><?php echo $_post->getPublishDate('F d, Y') ?></div></div>
                            </div>
                        <?php } ?>
                        <div class="post-text">
                            <div class="post-title clearfix">
                                <a class="post-item-link"
                                   href="<?php echo $_post->getPostUrl() ?>">
                                    <?php echo $block->escapeHtml($_post->getTitle()) ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

            <?php } ?>
        </div>
    </div>
    <?php } ?>
<?php } ?>