<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_category = $block->getCurrentCategory();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

$_imgHtml = '';
if ($_imgUrl = $_category->getImageUrl()) {
    $_imgHtml = '<div class="shop_header with_featured_img">
        <img class="shop_header_bkg bg-loaded" src="' . trim($_imgUrl) .'" alt=""/>
    </div>';
    echo $_imgHtml;
}
?>