<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$headerBuilderHelper = $this->helper('CleverSoft\CleverTheme\Helper\HeaderData');
$settingData = $headerBuilderHelper->getSettingData();

?>
<div class="header-compare item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="icon action compare" title="<?php /* @escapeNotVerified */ echo __('Compare Products') ?>"
       data-bind="attr: {'href': compareProducts().listUrl}"
    >
    	<i class="cs-font <?=isset($settingData->{'_customize-radio-compare_icon'}) && $settingData->{'_customize-radio-compare_icon'} ? $settingData->{'_customize-radio-compare_icon'} : 'clever-icon-refresh-2';?>"></i>
        <!-- ko if: compareProducts().count -->
        <span class="counter-number counter qty" data-bind="text: compareProducts().countCaption"></span>
        <!-- /ko -->
        <?php if(isset($settingData->{'_customize_header_compare_title'}) && $settingData->{'_customize_header_compare_title'} == '1'):?>
            <span class="compare-text">My Compare</span>
        <?php endif?>
    </a>
</div>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>
