<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

 /** @var $block \CleverSoft\CleverBuilder\Block\Adminhtml\Wysiwyg\Images\Content */
?>

<div data-mage-init='{"mediabrowser": <?= $block->escapeHtml($block->getFilebrowserSetupObject()) ?>}'>
    <div class="side-col"><?= $block->getChildHtml('wysiwyg_images.tree') ?></div>
    <div class="main-col">
        <div class="insert-title" id="content_header">
            <div class="insert-title-inner">
                <div class="insert-actions">
                    <button id="new_folder" title="Create Folder..." type="button" class="action-default scalable save" data-ui-id="wysiwyg-images-content-new-folder-button">
                        <span>Create Folder...</span>
                    </button>

                    <button id="insert_files" title="Insert File" type="button" class="action-default scalable save primary" data-ui-id="wysiwyg-images-content-insert-files-button">
                        <span>Insert File</span>
                    </button>

                    <button id="delete_files" title="Delete File" type="button" class="action-default scalable delete" data-ui-id="wysiwyg-images-content-delete-files-button">
                        <span>Delete File</span>
                    </button>
                </div>
                <div class="title"><?= $block->escapeHtml($block->getHeaderText()) ?></div>
            </div>
        </div>
        <div id="error-message" data-action="show-error"></div>
        <div id="contents-uploader" class="contents-uploader"><?= $block->getChildHtml('wysiwyg_images.uploader') ?></div>
        <div id="contents"></div>
    </div>
</div>
