<?php 
/**
 * @category    CleverSoft
 * @package     CleverSocialLogin
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?> 
<?php if ($this->getHelper()->hasButtons()) : ?>
    <div class="pslogin-block pslogin-login pslogin-login-popup pslogin-block-head" data-mage-init='{"pslogin":{}}'>

        <div class="pslogin-spacer pslogin-clearfix">
                <span class="pslogin-title"><?php echo __('Login with your social account'); ?></span>
        </div>

        <div class="pslogin-buttons <?php echo $this->showLoginFullButtons() ? 'pslogin-buttons-showfull' : ''; ?>">
            <ul class="pslogin-clearfix">
                <?php foreach ($this->getPreparedButtons() as $button) : ?>
                    <li class="pslogin-button <?php echo $button['type']; ?> <?php echo empty($button['visible']) ? 'pslogin-hidden' : 'pslogin-visible'; ?>" <?php echo empty($button['visible']) ? 'style="display: none;"' : ''; ?>
                        title="<?php echo $this->escapeHtml($button['login_text']); ?>">
                        <a class="pslogin-button-link pslogin-button-click" rel="nofollow"
                           href="javascript:void(0);" data-href="<?php echo $button['href']; ?>"
                           data-width="<?php echo $button['popup_width']; ?>"
                           data-height="<?php echo $button['popup_height']; ?>">
                        <span class="pslogin-button-auto">
                            <span class="pslogin-button-icon"></span>
                            <span
                                class="pslogin-button-text"><?php echo $this->escapeHtml($button['login_text']); ?></span>
                        </span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>

            <?php if ($this->getPreparedButtons('hidden')) : ?>
                <div class="pslogin-spacer pslogin-clearfix pslogin-showmore">
                    <table>
                        <tr>
                            <td>
                                <div class="pslogin-border"></div>
                            </td>
                            <td class="w100">
                                <div
                                    class="pslogin-showmore-button pslogin-bordertext"><?php echo __('show more'); ?></div>
                            </td>
                            <td>
                                <div class="pslogin-border"></div>
                            </td>
                        </tr>
                    </table>
                </div>
            <?php endif; ?>
        </div>

    </div>
    <div style="clear: both;"></div>

    <script>
        var showFullButtonsAfterViewMore = <?php echo $this->showFullButtons()? 'true' : 'false'; ?>;
        if (window.psloginButtons) {
            requirejs(['pslogin']);
        }
    </script>
<?php endif; ?>
