<?php
function top_get_categories_mobile() {
    $objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManagerr->create('Magento\Catalog\Model\Category');
    $tree = $category->getTreeModel();
    $tree->load();
    $ids = $tree->getCollection()->addFieldToFilter('is_active', array('eq'=>'1'))->getAllIds();
    $arrayCategories = array();
    if ($ids) {
        foreach ($ids as $id) {
            $cat = $objectManagerr->create('Magento\Catalog\Model\Category');
            $cat->load($id);
            $arrayCategories[$id] = $cat;
        }
        return $arrayCategories;
    }
}
$arrayCategories = top_get_categories_mobile();
    
function top_createTree_mobile($array, $currentParent, $currLevel = 0, $prevLevel = -1) {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $helper = $objectManager->create('CleverSoft\CleverSearchAutoComplete\Helper\Data');
    $searchMultipleCategories = $helper->getSearchMultipleCategories();
    if ($searchMultipleCategories) {
        foreach ($array as $categoryId => $category) {
            if ($currentParent == $category['parent_id']) {
                if ($currLevel > $prevLevel)
                echo '<ul class="top-tree__list">';
                if ($currLevel == $prevLevel)
                    echo " </li> ";
                
                echo '
                    <li class="top-tree__items">';
                
                echo '<a href="javascript:;" data-id="'.$categoryId.'">';
                    echo '<span>'.$category['name'].'</span>';
                echo '</a>';
                if ($currLevel > $prevLevel) {
                    $prevLevel = $currLevel;
                }
                $currLevel++;
                top_createTree_mobile($array, $categoryId, $currLevel, $prevLevel);
                $currLevel--;
            }
        }
    } else {
        foreach ($array as $categoryId => $category) {
            if ($currentParent == $category['parent_id']) {
                if($currLevel == 0) {
                    if ($currLevel > $prevLevel)
                    echo '<ul class="top-tree__list">';
                    if ($currLevel == $prevLevel)
                        echo " </li> ";
                    
                    echo '
                        <li class="top-tree__items">';
                    
                    echo '<a href="javascript:;" data-id="'.$categoryId.'">';
                        echo '<span>'.$category['name'].'</span>';
                    echo '</a>';
                    if ($currLevel > $prevLevel) {
                        $prevLevel = $currLevel;
                    }
                    $currLevel++;
                    top_createTree_mobile($array, $categoryId, $currLevel, $prevLevel);
                    $currLevel--;
                }
            }
        }
    }
    
    if ($currLevel == $prevLevel)
        echo " </li></ul> ";
}
?>

<div class="inner">
    <a href="javascript:;" class="current-cat-mobile" data-role="trigger">
        <span><?php echo __('All Categories');?></span>
        <i class="cs-font clever-icon-down"></i>
    </a>
</div>
<div id="top_sidetree_mobile" style="display: none">
    <div id="top_tree_mobile" class="top-tree">
        <ul class="top-tree__parent"><li><a href="javascript:;" data-id=""><?php echo __('All Categories');?></a></li></ul>
        <?php top_createTree_mobile($arrayCategories, 2); ?>
    </div>
</div>

<script>
    require(['jquery'], function($){ 
        $('.current-cat-mobile').click(function() {
            if($(this).hasClass('active')){
                $('#top_sidetree_mobile').fadeOut();
            }else {
                $('#top_sidetree_mobile').fadeToggle();
            }
            $(this).toggleClass( "active" );
        });
        $(document).mouseup(function (e) {
            if (!$('#top_sidetree_mobile').is(e.target) && $('#top_sidetree_mobile').has(e.target).length === 0)
            {
               // $('#top_sidetree_mobile').fadeOut();
            }

        });
        $('#top_tree_mobile a').click(function() {
            var text = $(this).html();
            var value = $(this).attr('data-id');
            $('.current-cat-mobile span').html(text);
            $('input[name="cat"]').val(value);
            $('#top_sidetree_mobile').fadeOut();
        });
        $(document).ready(function(){
            $('.form-group').append('<a href="javascript:;" class="btn-close" style="display: none;"><i class="fa fa-times-circle-o"></i></a>');
        });
        $(document).keypress(function(){
            $('.btn-close').click(function(){
                $('.input-text').val('');
                $('.btn-close').hide();
                if($('.input-text').val('')){
                    $('.searchsuite-autocomplete').fadeOut();
                }
            });
        });
    });
</script>