<span class="area-arrow"></span>
<h4><?php echo __('Welcome'); ?></h4>
<ul class="header links user_area"><div class="block account-nav">
    <div class="title account-nav-title">
        <strong></strong>
    </div>
    <div class="content account-nav-content" id="account-nav">
        <ul class="nav items">
        	<li class="nav item">
        		<a href="<?=$this->getUrl('customer/account');?>">My Account</a>
        	</li>
        	<li class="nav item">
        		<a href="<?=$this->getUrl('customer/account/address');?>">Address Book</a>
        	</li>
        	<li class="nav item">
        		<a href="<?=$this->getUrl('customer/account/edit');?>">Account Information</a>
        	</li>
        	<li class="nav item">
        		<a href="<?=$this->getUrl('customer/account/logout');?>">Logout</a>
        	</li>
        </ul>
    </div>
</div>
</ul>