<?php
$desktopData = $this->getFooterDesktopData();
$mobileData = $this->getFooterMobileData();
$storeId = $this->getCurrentStore();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$settings = '';
if ($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',$storeId)->getFirstItem()->getId()) {
    $settings = json_decode($objectManager->create('CleverSoft\CleverTheme\Model\FooterBlock')->getCollection()->addFieldToFilter('store_id',$storeId)->getFirstItem()->getFooterStyle());
}
if($settings){
    $data = isset($settings->footer) ? $settings->footer : '{}';
}
?>
<?php if($storeId):?>
<div class="toggle-header-builder">
    <h4>Use Footer Builder</h4>
    <small>Use Footer Builder to custom footer layout for specific store view.</small>
    <div class="onoffswitch">
        <input type="checkbox" name="settings[footer][onoffswitch-footerbuilder]" class="onoffswitch-checkbox" id="footeronoffswitch" <?php echo isset($data->{'onoffswitch-footerbuilder'}) && $data->{'onoffswitch-footerbuilder'} ? 'checked' : ''?>>
        <label class="onoffswitch-label" for="footeronoffswitch"></label>
    </div>
</div>
<div class="wp-full-overlay footer-full-overlay expanded in-sub-panel section-open preview-desktop" style="display:none">
<?php else:?>
<div class="wp-full-overlay footer-full-overlay expanded in-sub-panel section-open preview-desktop">
<?php endif;?>
    <script type="text/html" id="tmpl-customize-panel-default-content">
        <li class="panel-meta customize-info accordion-section <# if ( ! data.description ) { #> cannot-expand<# } #>">

        </li>
    </script>
    <script type="text/html" id="tmpl-customize-panel-default">
        <li id="accordion-panel-{{ data.id }}"
            class="accordion-section control-section control-panel control-panel-{{ data.type }}">

        </li>
    </script>

    <script type="text/html" id="tmpl-customize-section-default">
        <li id="accordion-section-{{ data.id }}"
            class="accordion-section control-section control-section-{{ data.type }}">

        </li>
    </script>
    <script type="text/html" id="tmpl-customize-section-themes">
        <li id="accordion-section-{{ data.id }}" class="theme-section">
            <div class="customize-themes-section themes-section-{{ data.id }} control-section-content themes-php">
            </div>
        </li>
    </script>

    <script type="text/html" id="footer-cleversoft--builder-panel">
        <div class="">
            <div class="cleversoft--cb-inner">
                <div class="cleversoft--cb-header">
                    <div class="cleversoft--cb-devices-switcher">
                    </div>
                    <div class="cleversoft--cb-actions">
                        <button data-id="footer_templates" class="focus-section button button-secondary" onclick="openFooterModal(event, 'footer_templates')">Templates</button>
                        <button id="footer_clear_section" class="focus-section button button-secondary">Clear</button>
                    </div>
                </div>
                <div class="cleversoft--cb-body"></div>
            </div>
        </div>
    </script>


    <script type="text/html" id="footer-cleversoft--cb-panel">
        <div class="cleversoft--cp-rows">

            <# if ( ! _.isUndefined( data.rows.top ) ) { #>
            <div class="cleversoft--row-top cleversoft--cb-row" data-id="{{ data.id }}_top">
                <a class="cleversoft--cb-row-settings" title="{{ data.rows.top }}" data-id="top_bar" href="#"></a>
                <div class="cleversoft--row-inner">
                    <div class="row--grid">
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                    <div class="cleversoft--cb-items grid-stack gridster" data-id="top"></div>
                </div>
            </div>
            <# } #>

            <# if ( ! _.isUndefined( data.rows.main ) ) { #>
            <div class="cleversoft--row-main cleversoft--cb-row" data-id="{{ data.id }}_main">
                <a class="cleversoft--cb-row-settings" title="{{ data.rows.main }}" data-id="main_bar"
                   href="#"></a>

                <div class="cleversoft--row-inner">
                    <div class="row--grid">
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                    <div class="cleversoft--cb-items grid-stack gridster" data-id="main"></div>
                </div>
            </div>
            <# } #>


            <# if ( ! _.isUndefined( data.rows.bottom ) ) { #>
            <div class="cleversoft--row-bottom cleversoft--cb-row" data-id="{{ data.id }}_bottom">
                <a class="cleversoft--cb-row-settings" title="{{ data.rows.bottom }}"
                   data-id="bottom_bar" href="#"></a>
                <div class="cleversoft--row-inner">
                    <div class="row--grid">
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                    <div class="cleversoft--cb-items grid-stack gridster" data-id="bottom"></div>
                </div>
            </div>
            <# } #>
        </div>


        <# if ( ! _.isUndefined( data.rows.sidebar ) ) { #>
        <div class="cleversoft--cp-sidebar">
            <div class="cleversoft--row-bottom cleversoft--cb-row" data-id="{{ data.id }}_sidebar">
                <a class="cleversoft--cb-row-settings" title="{{ data.rows.sidebar }}" data-id="sidebar"
                   href="#"></a>
                <div class="cleversoft--row-inner">
                    <div class="cleversoft--cb-items cleversoft--sidebar-items" data-id="sidebar"></div>
                </div>
            </div>
        </div>
        <# } #>

    </script>

    <script type="text/html" id="footer-cleversoft--cb-item">
        <div class="grid-stack-item item-from-list for-s-{{ data.section }}"
             title="{{ data.name }}"
             data-id="{{ data.id }}"
             data-control="{{ data.control }}"
             data-gs-x="{{ data.x }}"
             data-gs-y="{{ data.y }}"
             data-gs-width="{{ data.width }}"
             data-df-width="{{ data.width }}"
             data-gs-height="1"
        >
            <div class="item-tooltip" data-section="{{ data.id }}">{{ data.name }}</div>
            <div class="grid-stack-item-content">
                <span class="cleversoft--cb-item-name" data-id="{{ data.id }}">{{ data.name }}</span>
                <span class="cleversoft--cb-item-remove cleversoft-cb-icon"></span>
                <span class="cleversoft--cb-item-setting cleversoft-cb-icon" data-id="{{ data.id }}"></span>
            </div>
        </div>
    </script>

    <script>
        var _footerBuilderSettings = {
            "changeset": {
                "lockUser": null
            },
            "timeouts": {"previewFrameSensitivity": 2000},
            "theme": {"_canInstall": true},
            "url": {
                "preview": ""
            },
            "panels": {
                "footer_settings": {
                    "id": "footer_settings",
                    "description": "",
                    "priority": 1,
                    "type": "cleversoft_panel",
                    "title": "Footer",
                    "content": "",
                    "active": true,
                    "instanceNumber": 11
                }
            },
            "sections": {
                "footer_builder_panel": {
                    "id": "footer_builder_panel",
                    "description": "",
                    "priority": 160,
                    "panel": "footer_settings",
                    "type": "cleversoft_section",
                    "description_hidden": false,
                    "title": "Footer Builder",
                    "content": "",
                    "active": true,
                    "instanceNumber": 48,
                    "customizeAction": "Customizing &#9656; Footer"
                }
            },
            "autofocus": []
        };

        _footerBuilderSettings.controls = {};
        _footerBuilderSettings.settings = {};

        (function (c) {

            c["footer_builder_panel"] = {
                "settings": {"default": "footer_builder_panel"},
                "type": "cleversoft",
                "priority": 10,
                "active": true,
                "section": "footer_builder_panel",
                "content": "<li id=\"customize-control-footer_builder_panel\" class=\"customize-control customize-control-cleversoft-js_raw\">\r\n                <\/li>",
                "label": "Footer Builder",
                "description": "",
                "instanceNumber": 146,
                "device_settings": false,
                "value": {
                    "desktop": <?php echo $desktopData ? $desktopData : '{}';?>,
                    "mobile": <?php echo $mobileData ? $mobileData : '{}';?>,
                },
                "default": null,
                "placeholder": "",
                "fields": [],
                "setting_type": "js_raw",
                "required": null,
                "devices": null,
                "reset_controls": [],
                "min": 0,
                "max": 700,
                "step": 1,
                "unit": false
            }

        })(_footerBuilderSettings.controls);
    </script>
</div>
<input id="footerbuilder-desktop-data" name="footerbuilder-desktop-data" type="hidden" value='<?php echo $desktopData ? $desktopData : '{}';?>'>
<input id="footerbuilder-mobile-data" name="footerbuilder-mobile-data" type="hidden" value='<?php echo $mobileData ? $mobileData : '{}';?>'>
<!-- popup setting -->
<div id="footerbuilder-popup-footer_templates" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer_templates.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-top_bar" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer_top_bar.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-main_bar" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer_main_bar.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-bottom_bar" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer_bottom_bar.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-language" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-language.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-copyright" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/copyright.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-social-icon" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/social-icon.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-newsletter" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/newsletter.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-payment-icon" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/payment-icon.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-widget-1" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-widget-1.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-widget-2" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-widget-2.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-widget-3" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-widget-3.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-widget-4" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-widget-4.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-widget-5" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-widget-5.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-widget-6" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-widget-6.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-widget-7" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-widget-7.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-widget-8" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-widget-8.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-html-1" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-html-1.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<div id="footerbuilder-popup-footer-html-2" class="footerbuilder-modal">
    <?php
    $template = "CleverSoft_CleverTheme::popup/footer-html-2.phtml";
    echo $this->getLayout()
        ->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate($template)
        ->toHtml(); ?>
</div>
<script>
    require(['jquery', 'jquery/ui', 'footerbuilder'], function($){
        if($('input[name="settings[footer][onoffswitch-footerbuilder]"]').prop('checked')) {
            $(".footer-full-overlay").css("display","block");
        }
        $('input[name="settings[footer][onoffswitch-footerbuilder]"]').change(function(e){
            if($('input[name="settings[footer][onoffswitch-footerbuilder]"]').prop('checked')) {
                $(".footer-full-overlay").css("display","block");
            } else {
                $(".footer-full-overlay").css("display","none");
                $(".headerbuilder-modal").css("display","none");
            }
        });
    });
</script>

<script>
    function openFooterModal(evt, popup) {
        evt.preventDefault();
        var i, poupcontent, popup_link;
        poupcontent = document.getElementsByClassName("footerbuilder-modal");
        for (i = 0; i < poupcontent.length; i++) {
            poupcontent[i].style.display = "none";
        }
        popup_link = "footerbuilder-popup-"+popup;
        document.getElementById(popup_link).style.display = "block";
    }
</script>