<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$theme = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$_imageHelper = $this->helper('CleverSoft\CleverTheme\Helper\Image');
$imgWidth = intval($theme->getCfg('category/image_width'));
$imgHeight = intval($theme->getCfg('category/image_height'));
//Image aspect ratio settings
$keepAspectRatio = $theme->getCfg('category/aspect_ratio');

if ($keepAspectRatio)
{
    $imgHeight = 0; //Height will be calculated automatically (based on width) to keep the aspect ratio
    $catViewKeepFrame = FALSE;
}
else
{
    $catViewKeepFrame = TRUE;
}

$_columnCount = $theme->getCfg('category_grid/column_count');
$showWishlist = $theme->getCfg('category_grid/display_addtowishlist');
$showCompare = $theme->getCfg('category_grid/display_addtocompare');
$showCart = $theme->getCfg('category_grid/display_addtocart');
$showSize = $theme->getCfg('category_grid/display_size');
$showPrice = $theme->getCfg('category_grid/display_price');
$showColor = $theme->getCfg('category_grid/display_color');
$showRating = $theme->getCfg('category_grid/display_rating');
$showSwatchAttributes = $theme->getCfg('category_grid/display_swatch_attributes');
$showProductName = $theme->getCfg('category_grid/display_productname');
$lazyload = $theme->getCfg('category/lazyload') == 1 ? 'true' : 'false';
$min_height_img_lazyload = $theme->getCfg('category/lazy_load_min_height');
$icon = $theme->getCfg('responsive/iconlazyload');
if (!empty($icon)) {
    $image = $icon;
    $om = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $om->create('Magento\Store\Model\StoreManagerInterface');
    $image_url = $storeManager->getStore()
            ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'lazyload/' . $image;
} else {
    $image_url = $block->getViewFileUrl('CleverSoft_CleverTheme::images/transparent.gif');
}
$image_alt_url = $block->getViewFileUrl('CleverSoft_CleverTheme::images/transparent.gif');

$tooltip = 'tooltip';

$containerClasses = "grid products-grid products-grid-partitioned category-products-grid";
$itemgridClasses = 'itemgrid zoo-itemgrid-adaptive';

if ($theme->getCfg('category_grid/enable_border_boxshadow'))
    $containerClasses .= ' enable_border_boxshadow';
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;

            $canItemsAddToCart = false;
            if ($theme->getCfg('product_page/related_checkbox'))
            {
                $canItemsAddToCart = $block->canItemsAddToCart();
            }

            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>
<?php if ($exist):?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
    <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
        <?php endif; ?>
        <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
            <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
            <?php if ($type == 'related' && $canItemsAddToCart): ?>
            <div class="block-actions">
                <?php /* @escapeNotVerified */ echo __('Check items to add to the cart or') ?>
                <button type="button" class="action select" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
            </div>
            <?php endif; ?>
            <div class="<?php /* @escapeNotVerified */  echo $containerClasses; ?>">
                <ol class=" products list items product-items owl-carousel">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                    <?php $available = ''; ?>
                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                    <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product_hover item product product-item" style="display: none;">' : '</li><li class="product_hover item product product-item" style="display: none;">' ?>
                    <?php else: ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product_hover item product product-item">' : '</li><li class="product_hover item product product-item">' ?>
                    <?php endif; ?>
                    <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?> <?php if ($alternative_img = $theme->getAltImgHtml($_item, $imgWidth, $imgHeight, 'category_page_grid')): ?> have-alternative-image <?php endif; ?>">
                        <div class="zoo-inner-product-item-info">
                            <div class="zoo-product-image">
                                <div class="add-to-link">
                                    <?php if ($theme->getCfg('product_quickview/enable')): ?>
                                    <div class="zoo-quickview zoo_icon">
                                        <div class="effect-tooltip">
                                            <span class="tooltip"><?php /* @escapeNotVerified */ echo __('Quick View') ?></span>
                                            <i class="cs-font clever-icon-eye-5" rel="<?php echo $tooltip; ?>" data-original-title="<?php echo __('Quick View') ?>"></i>
                                        </div>
                                        <a class="product-quickview"  href="<?php echo $block->getUrl('cleversofttheme/product/view/id/' . $_item->getId()); ?>" data-id='quickview-<?php echo $_item->getId() ?>' style='display:none'><?php echo __('Quick View') ?>
                                        </a>
                                    </div>
                                    <?php endif; ?>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist != 'remove'): ?>
                                    <div class="zoo-wishlist zoo_icon" data-role="add-to-links">
                                        <a class="zoo_icon__link" href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>' data-action="add-to-wishlist" title="">
                                            <div class="effect-tooltip">
                                                <span class="tooltip"><?php /* @escapeNotVerified */ echo __('Add to Wishlist') ?></span>
                                                <i class="cs-font clever-icon-heart-1" rel="<?php echo $tooltip; ?>" data-original-title="<?php echo __('Add to Wishlist') ?>"></i>
                                            </div>
                                        </a>
                                    </div>
                                    <?php endif; ?>
                                    <?php if ($block->getAddToCompareUrl() && $showCompare != 'remove'): ?>
                                    <div class="zoo-compare zoo_icon" data-role="add-to-links">
                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                        <a class="zoo_icon__link" href="#" class="action tocompare" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'>
                                            <div class="effect-tooltip">
                                                <span class="tooltip"><?php /* @escapeNotVerified */
                                                    echo __('Add to Compare') ?></span>
                                                <i class="cs-font clever-icon-law-1" rel="<?php echo $tooltip; ?>" data-original-title="<?php echo __('Add to Compare') ?>"></i>
                                            </div>
                                        </a>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo" <?php if ($lazyload) echo 'style="min-height: ' . $min_height_img_lazyload . 'px"' ?> >
                                    <?php if (!$imgWidth): ?>
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                    <?php else: ?>
                                        <?php if(!$keepAspectRatio):?>
                                            <img data-src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight, 'category_page_grid'); ?>" src="<?php echo (!$lazyload) ? $_imageHelper->getImg($_item, $imgWidth, $imgHeight, 'category_page_grid') : $image_url; ?>"
                                             class="<?php if ($lazyload) echo "clazyload"; ?> product-image-photo"
                                             alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" width="<?php echo $imgWidth ?>"/>
                                        <?php else:?>
                                            <img data-src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight, 'category_page_grid'); ?>" src="<?php echo (!$lazyload) ? $_imageHelper->getImg($_item, $imgWidth, $imgHeight, 'category_page_grid') : $image_url; ?>"
                                             class="<?php if ($lazyload) echo "clazyload"; ?> product-image-photo"
                                             alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" width="<?php echo $imgWidth ?>"/>
                                        <?php endif;?>
                                    <?php endif; ?>
                                    <?php if ($theme->getCfg('category/alt_image') && $theme->getAltImgHtml($_item, $imgWidth, $imgHeight, $image)): ?>
                                    <span class="product-img-additional alt-image2">
                                    <?php if(!$keepAspectRatio):?>
                                        <?php echo $theme->getAltImgHtml($_item, $imgWidth, $imgHeight, $image); ?>
                                    <?php else:?>
                                        <?php echo $theme->getAltImgHtml($_item, $imgWidth, $imgHeight, $image); ?>
                                    <?php endif;?>
                                    </span>
                                    <?php endif; ?>
                                </a>
                                <?php if ($showCart != 'remove'): ?>
                                <div class="add_to_cart">
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                        <button class="action tocart btn-addcart" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button">
                                            <i class="cs-font clever-icon-cart-6"></i>
                                            <span class="btn-addcart__title"><?php echo __('Add to Cart') ?></span>
                                        </button>
                                        <?php else: ?>
                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                            ?>
                                        <button class="action tocart btn-addcart"
                                            data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                            type="button">
                                            <i class="cs-font clever-icon-cart-6" rel="<?php echo $tooltip; ?>" data-original-title="<?php echo __('Add to Cart') ?>"></i>
                                            <span class="btn-addcart__title"><?php echo __('Add to Cart') ?></span>
                                        </button>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php endif; ?>
                            </div>
                            <div class="product details product-item-details">
                                <div class="hover-area product_shop_loop">
                                    <?php if ($showProductName != 'remove'): ?>
                                    <h5 class="product-item-name ">
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                            href="<?php /* @escapeNotVerified */
                                                echo $block->getProductUrl($_item) ?>"
                                            class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </h5>
                                    <?php endif; ?>
                                    <?php if ($templateType && $showRating != 'remove'): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                    <?php endif; ?>
                                    <?php if ($showPrice != 'remove'): ?>
                                    <?php echo $block->getProductPriceHtml($_item, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE); ?>
                                    <?php endif; ?>
                                </div>
                                <?php if ($showSwatchAttributes != 'remove'): ?>
                                <?php echo $block->getColorSwatchDetailsHtml($_item); ?>
                                <?php endif; ?>
                                <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                <div class="field choice related">
                                    <input type="checkbox" class="checkbox related" id="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="related_products[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                    <label class="label" for="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></label>
                                </div>
                                <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
    <script>
        require([
            'jquery',
            'jQueryLibMin'
        ], function ($) {
            $(document).ready(function(){
                $(function(){
                  $(document).on({
                      mouseenter: function () {
                        var imgage_additional = $(this).find('.imgage-additional');
                        var zoo_image = $(this).find('.zoo-product-image');
                        zoo_image.addClass('hover-image-loading');
                        imgage_additional.attr('src', imgage_additional.attr('data-src'));
                        zoo_image.addClass('hover-image-loaded');
                        zoo_image.removeClass('hover-image-loading');
                      },
                      mouseleave: function () {

                      }
                  }, ".product-item-info");
                });
                (function($) {
                  $(document).ready(function() {
                    $(".owl-carousel").owlCarousel({
                        loop:true,
                        margin:30,
                        responsiveClass:true,
                        dots: false,
                        navText: ['<i class="cs-font clever-icon-prev"></i>','<i class="cs-font clever-icon-next"></i>'],
                        responsive:{
                            0:{
                                items:2,
                                nav:false,
                                dots: true
                            },
                            600:{
                                items:3,
                                nav:false
                            },
                            1000:{
                                items:4,
                                nav:true,
                                loop:false
                            }
                        }
                    });
                  });
                }) (jQuery);
            });
        });
    </script>
<?php endif;?>
