<?php
/**
 * @category    CleverSoft
 * @package     CleverTheme
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>

<link rel="stylesheet" href="<?php echo $this->helper('CleverSoft\CleverTheme\Helper\Cssgen')->getDesignFile();?>" />
<link rel="stylesheet" href="<?php echo $this->helper('CleverSoft\CleverTheme\Helper\Cssgen')->getLayoutFile();?>" />