<?php
$headerBuilderHelper = $this->helper('CleverSoft\CleverTheme\Helper\HeaderData');
$settingData = $headerBuilderHelper->getSettingData();

$staticBlock = isset($settingData->{'_customize-select-html-3'}) && $settingData->{'_customize-select-html-3'} ? $settingData->{'_customize-select-html-3'} : '';
?>
<?php if ($staticBlock): ?>
    <?php if (isset($settingData->{'_customize-input-html-3_margin'}) && $settingData->{'_customize-input-html-3_margin'}): ?>
        <div style="margin: <?php echo $settingData->{'_customize-input-html-3_margin'} ?>">
    <?php endif; ?>
    <?php echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId($staticBlock)
        ->toHtml(); ?>
    <?php if (isset($settingData->{'_customize-input-html-3_margin'}) && $settingData->{'_customize-input-html-3_margin'}): ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
