<?php
$headerBuilderHelper = $this->helper('CleverSoft\CleverTheme\Helper\HeaderData');
$settingData = $headerBuilderHelper->getSettingData();

$menu = isset($settingData->{'_customize-select-menu-mobile'}) && $settingData->{'_customize-select-menu-mobile'} ? $settingData->{'_customize-select-menu-mobile'} : '';
?>
<?php if($menu):?>
    <div class="menu-mobile <?=isset($settingData->{'_customize-input-custom-class_primary_menu-mobile'}) && $settingData->{'_customize-input-custom-class_primary_menu-mobile'} ? $settingData->{'_customize-input-custom-class_primary_menu-mobile'} : ''?>">
        <?php echo $this->getLayout()->createBlock("CleverSoft\CleverMegaMenus\Block\Widget\Megamenu")->setMenu($menu)->setTemplate("menu.phtml")->toHtml(); ?>
    </div>
<?php endif;?>
