<?php
$helper = $this->helper('CleverSoft\CleverBuilder\Helper\Data');
$isPreview = $helper->getCustomerEnablePanel();
$style = $this->getData('style');
$weight = $this->getData('weight');
$width = $this->getData('width');
$color =  $this->getData('color');
$align = $this->getData('align');
$gap = $this->getData('gap');

$style_divider = $style ? "border-top-style: $style" : "border-top-style: solid";
$weight_divider = $weight ? "border-top-width: $weight"."px" : "border-top-width: 3px";
$width_divider = $width ? "width: $width"."%" : "width: 5%";
$color_divider = $color ? "border-top-color: $color" : "border-top-color: #999";
$height_divider__top = $gap ? "padding-top: $gap"."px" : "";
$height_divider__bottom = $gap ? "padding-bottom: $gap"."px" : "";
$style_parent = $height_divider__top . ';' . $height_divider__bottom;
$style_child = $style_divider .';' . $weight_divider . ';' . $width_divider . ';' . $color_divider;
?>
<div class="<?=$this->getData('align')?> global-element element-divider <?php if($isPreview) echo "cs-live-preview"?>" style="<?= $style_parent?>">
	<span class="element-divider__separator" style="<?= $style_child?>"></span>
	<?php if($isPreview) { ?>
        <span class="cs-edit-element-section" style="display:none"><i class="fa fa-edit" aria-hidden="true"></i></span>
    <?php } ?>
</div>