<?php
$helper = $this->helper('CleverSoft\CleverBuilder\Helper\Data');
$isPreview = $helper->getCustomerEnablePanel();
$heightData = $this->getData('height');
$height = $heightData ? "height: $heightData"."px" : "";
$style = $height;
?>
<div class="global-element <?php if($isPreview) echo "cs-live-preview"?>">
    <div class="gap clearfix" style="<?= $style ? "$style" : "height: 30px"?>"></div>
    <?php if($isPreview) { ?>
        <span class="cs-edit-element-section" style="display:none"><i class="fa fa-edit" aria-hidden="true"></i></span>
    <?php } ?>
</div>