<?php
/**
 * @category    CleverSoft
 * @package     CleverBuilder
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author      ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php

use Magento\Framework\App\Action\Action;
$_id = $this->getConfig('id')?$this->getConfig('id'):$this->getData('id');
$_title = $this->getConfig('widget_title') ? $this->getConfig('widget_title') : $this->getData('widget_title');
$_sub_title = $this->getData('widget_sub_title') ? $this->getData('widget_sub_title') : $this->getConfig('widget_sub_title');
$t = microtime();
$tab = $this->getData('tab');
$lazyload = $this->getData('lazyload');
if(is_null($lazyload)) $lazyload = false;
$min_height_img_lazyload = $this->getData('height_image');

$image_url = $this->getViewFileUrl('CleverSoft_CleverBuilder::images/transparent.gif');
$image_alt_url = $this->getViewFileUrl('CleverSoft_CleverBuilder::images/transparent.gif');
?>
<div class="<?php echo $this->getData('classes') ?> zoo-product-collection02" id="<?php echo $_id ?>">
    <?php if ($_title || $_sub_title): ?>
        <div class="zoo-main-heading">
            <?php if($_title) : ?>
                <div class="zoo-heading-wrapper-title">
                    <h3><span><?php echo $_title ?></span></h3>
                </div>
            <?php endif; if($_sub_title): ?>
                <div class="zoo-heading-wrapper-sub-title">
                    <h3><span><?php echo $_sub_title ?></span></h3>
                </div>
            <?php endif; ?>
        </div>
    <?php endif;
    ?>
    <?php if ($exist = ($this->getData('collection') && $this->getData('collection')->getSize())): ?>
        <?php
        $type = 'widget-product-grid';

        $mode = 'grid';

        $count = $this->getData('collection') ? $this->getData('collection')->count() : 0;
        //        $carousel = $this->getData('carousel');

        $row = (int)$this->getData('limit');
        $column = 1;

        $image = 'new_products_content_widget_grid';
        $items = $this->getData('collection')->getItems();

//        $showWishlist = true;
//        $showCompare = true;
//        $showCart = true;
        // new config
        $showWishlist = $this->getData('display_addtowishlist');
        $showCompare = $this->getData('display_addtocompare');
        $showCart = $this->getData('display_addtocart');
        $showSize = $this->getData('display_size');
        $showPrice = $this->getData('display_price');
        $showColor = $this->getData('display_color');
        $showRating = $this->getData('display_rating');
        $showProductName = $this->getData('display_productname');

        ///

        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $_imageHelper = $this->helper('CleverSoft\CleverBuilder\Helper\Product\Image');
        $description = false;
        $dataHelpder = $this->helper('CleverSoft\CleverBuilder\Helper\Product\Data');
        $imgWidth = $this->getData('image_width');
        $imgHeight = $this->getData('image_height');

        //Image aspect ratio settings
        $keepAspectRatio = $this->getData('aspect_ratio');
        if ($keepAspectRatio == 'true' || $keepAspectRatio == '1') {
            $imgHeight = 0; //Height will be calculated automatically (based on width) to keep the aspect ratio
            $catViewKeepFrame = FALSE;
        } else {
            $catViewKeepFrame = TRUE;
        }

        $extClass = '';
        ?>
        <div class="block widget zoo-block-products-list <?php /* @escapeNotVerified */
        echo $mode; ?>">
            <div class="block-content">
                <?php $i = 0;
                foreach ($items as $_item): ?>
                <?php /* @escapeNotVerified */
                echo '<!-- ' . $image . '-->' ?>
                <?php if (($row > 1 && $i % $row == 0)): ?>
                <div class="products-<?php /* @escapeNotVerified */
                echo $mode; ?> <?php /* @escapeNotVerified */
                echo $mode; ?>">
                    <ol class="product-items <?php /* @escapeNotVerified */
                    echo $type; ?>">
                        <?php endif ?>

                        <?php $i++ ?>
                        <?php /* @escapeNotVerified */
                        echo ($i == 1) ? '<li class="'. $extClass .'">' : '</li><li class="' . $extClass .'">';
                        ?>
                        <div class="product-add-form product-item-cleverSwatchRenderer">
                            <form action="<?php /* @escapeNotVerified */ echo $this->getSubmitUrl($_item) ?>" method="post"
                                  id="product_addtocart_form"<?php if ($_item->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                <input type="hidden" name="selected_configurable_option" value="" />
                                <input type="hidden" name="related_product" id="related-products-field" value="" />
                                <?php echo $this->getBlockHtml('formkey')?>
                                <div class="product-item-info">
                                    <div class="zoo-inner-product-item-info">
                                        <a href="<?php /* @escapeNotVerified */
                                        // Lazyload Kien Update icon image to spin css3
                                        echo $this->getProductUrl($_item) ?>" class="product-item-photo" style="min-height: <?php echo $min_height_img_lazyload; ?>px; width: <?php echo $this->getData('image_width') ?>px;">

                                            <?php echo $dataHelpder->getLabel($_item); ?>
                                            <?php if(!$imgWidth) : ?>
                                                <?php echo $this->getImage($_item, $image)->toHtml(); ?>
                                            <?php
                                            ////this else is for full width image - Hạnh issue
                                            else: ?>
                                                <?php if(!$keepAspectRatio):?>
                                                    <img <?php if($lazyload): ?> width="<?php echo $imgWidth ?>" class="clazyload product-image-photo" data-src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight,'category_page_grid'); ?>" src="<?php echo $image_url; ?>"
                                                    <?php else: ?>
                                                        class="product-image-photo" src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight,'category_page_grid'); ?>">
                                                    <?php endif; ?>
                                                <?php else:?>
                                                    <img <?php if($lazyload): ?> width="<?php echo $imgWidth ?>" class="clazyload product-image-photo" data-src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight,'category_page_grid'); ?>" src="<?php echo $image_url; ?>"
                                                    <?php else: ?>
                                                        class="product-image-photo" src="<?php echo $_imageHelper->getImg($_item, $imgWidth, $imgHeight,'category_page_grid'); ?>"
                                                    <?php endif; ?>
                                                <?php endif;?>
                                                    alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
                                            <?php endif; ?>
                                            <?php if (!$block->getData('alt_image') && $dataHelpder->getAltImgHtml($_item, $imgWidth, $imgHeight, $image)): ?>
                                                <?php if(!$keepAspectRatio):?>
                                                    <span class="product-img-additional alt-image">
                                                        <?php echo $dataHelpder->getAltImgHtml($_item, $imgWidth, $imgHeight, $image); ?>
                                                    </span>
                                                <?php else:?>
                                                    <span class="product-img-additional alt-image">
                                                        <?php echo $dataHelpder->getAltImgHtml($_item, $imgWidth, $imgHeight, $image); ?>
                                                    </span>
                                                <?php endif;?>
                                            <?php endif; ?>
                                        </a>
                                        <div class="product details product-item-details">
                                            <strong class="product-item-name">
                                                <a title="<?php echo $this->escapeHtml($_item->getName()) ?>"
                                                   href="<?php /* @escapeNotVerified */
                                                   echo $this->getProductUrl($_item) ?>"
                                                   class="product-item-link">
                                                    <?php echo $this->escapeHtml($_item->getName()) ?>

                                                </a>
                                            </strong>
                                            <?php
                                            echo $this->getProductPriceHtml($_item, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE);
                                            ?>

                                            <?php if ($templateType): ?>
                                                <?php echo $this->getReviewsSummaryHtml($_item, $templateType,true) ?>
                                            <?php endif; ?>
                                            <?php echo $this->getColorSwatchDetailsHtml($_item); ?>

                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <?php echo ($i == count($items)) ? '</li>' : '' ?>
                        <?php if ($i == $count || ($row > 1 && $i % $row == 0)): ?>
                        <!--                --><?php //if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
                    </ol>
                </div>
            <?php endif ?>
                <?php if ($i == $count): ?>
            </div>
            <?php endif ?>
            <?php endforeach ?>
        </div>
    <?php endif; ?>
    <?php if (!$this->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
</div>
<script>
    require([
        "jquery",

        "cleverProductMage"
    ], function ($,cleverProductMage) {
        $(function() {
            $(document).on({
                mouseenter: function () {
                    var imgage_additional = $(this).find('.imgage-additional');
                    var zoo_image = $(this).find('.zoo-product-image');
                    zoo_image.addClass('hover-image-loading');
                    imgage_additional.attr('src', imgage_additional.attr('data-src'));
                    zoo_image.addClass('hover-image-loaded');
                    zoo_image.removeClass('hover-image-loading');
                },
                mouseleave: function () {
                  
                }
            }, ".product-item-info");
            $('#<?php echo $_id ?>').cleverProductMage({
                animation: <?php echo $this->getData('animation') ? 'true' : 'false' ?>,
                parallax: <?php echo $this->getData('parallax') ? 'true' : 'false'?>,
//            carousel: <?php //echo $this->getConfig('carousel') ?>//,
                countdown: <?php echo $this->getData('countdown') ?>,
//            carouselConfig: {
//
//            },
             
            });
        });
    });
</script>