<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="form-cart-container">
		<div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
			<table id="shopping-cart-table"
				   class="cart items data table"
				   data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
				   "updateCartActionContainer": "#update_cart_action_container"}}'>
				<caption role="heading" aria-level="2" class="table-caption"><?php /* @escapeNotVerified */ echo __('Shopping Cart Items') ?></caption>
				<thead>
					<tr>
						<th class="col item" scope="col"><span><?php /* @escapeNotVerified */ echo __('Product Name') ?></span></th>
						<th class="col price hidden-xs" scope="col"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
						<th class="col qty" scope="col"><span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span></th>
						<th class="col subtotal hidden-xs" scope="col"><span><?php /* @escapeNotVerified */ echo __('Total') ?></span></th>
						<th class="col actions hidden-xs" scope="col"><span></span></th>
					</tr>
				</thead>
				<?php foreach ($block->getItems() as $_item): ?>
					<?php echo $block->getItemHtml($_item) ?>
				<?php endforeach ?>
			</table>
		</div>
		<div class="cart main actions">
			
			<button type="submit"
					name="update_cart_action"
					data-cart-item-update=""
					value="update_qty"
					title="<?php echo $block->escapeHtml(__('UPDATE CART')); ?>"
					class="action  update">
				<span><?php /* @escapeNotVerified */ echo __('UPDATE CART'); ?></span>
			</button>
			<input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
		</div>
	</div>
</form>
<?php echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>

