<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
$_matoHelper = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$headerBuilderHelper = $this->helper('CleverSoft\CleverTheme\Helper\HeaderData');
$settingData = $headerBuilderHelper->getSettingData();

$subtotal = $_matoHelper->getSubtotal();
$countItem = $_matoHelper->getCountItem();
?>
<?php $_item = $block->getItem() ?>
<?php if(isset($settingData->{'_customize_header_cart_mobile_style'}) && $settingData->{'_customize_header_cart_mobile_style'} == 'dropdown'):?>
    <div data-block="minicart-mobile" class="minicart-wrapper_dropdown">
        <?php if(isset($settingData->{'_customize_header_cart_mobile_title'}) && $settingData->{'_customize_header_cart_mobile_title'} == '1'):?>
            <span class="minicart-title">Cart</span>
        <?php endif?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>" class="action showcart_mobile icon minicart minicart-mobile minicart-dropdown <?=isset($settingData->{'_customize-radio-cart_mobile_icon_style'}) && $settingData->{'_customize-radio-cart_mobile_icon_style'} ? $settingData->{'_customize-radio-cart_mobile_icon_style'} : '';?>" data-bind="scope: 'minicart_content'">
            <?php if(isset($settingData->cart_mobileicon->value) && $settingData->cart_mobileicon->value):?>
                <img src="<?=$headerBuilderHelper->getMediaUrl().'cleversoft/headerbuilder/'.$settingData->cart_mobileicon->value?>" id="customize-control_header_cart_mobileicon_image" height="30" width="30" class="small-image-preview v-middle" >
            <?php else:?>
                <i class="cs-font <?=isset($settingData->{'_customize-radio-cart_mobile_icon'}) && $settingData->{'_customize-radio-cart_mobile_icon'} ? $settingData->{'_customize-radio-cart_mobile_icon'} : 'clever-icon-cart-14';?>"></i>
            <?php endif?>
            <!-- ko if: getCartParam('summary_count') -->
            <span class="counter qty empty"
                  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><?=$countItem?><!-- /ko --></span>
                <span class="counter-label">
                <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                    <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->
                </span>
            </span>
            <!-- /ko -->
        </a>
        <?php if(isset($settingData->{'_customize_header_cart_mobile_total'}) && $settingData->{'_customize_header_cart_mobile_total'} == '1'):?>
            <div class="subtotal-minicart" data-bind="html : getCartParam('subtotal')"><span class="price"><?=$subtotal?></div>
        <?php endif?>
        <?php if ($block->getIsNeedToDisplaySideBar()): ?>
            <div class="block block-minicart empty"
                 data-role="dropdownDialog"
                 data-mage-init='{"dropdownDialog":{
                    "appendTo":"[data-block=minicart-mobile]",
                    "triggerTarget":".showcart_mobile",
                    "timeout": "2000",
                    "closeOnMouseLeave": false,
                    "closeOnEscape": true,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":[]}}'>
                <div id="minicart-content-wrapper-mobile" data-bind="scope: 'minicart_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
                <?= $block->getChildHtml('minicart.addons') ?>
            </div>
        <?php endif ?>
        <script>
            window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig() ?>;
        </script>
        <script type="text/x-magento-init">
        {
            "[data-block='minicart-mobile']": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            },
            "*": {
                "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
            }
        }
        </script>
    </div>
<?php elseif(isset($settingData->{'_customize_header_cart_mobile_style'}) && $settingData->{'_customize_header_cart_mobile_style'} == 'off-canvas'):?>
    <div data-block="minicart-mobile" class="minicart-wrapper <?php if( $_matoHelper->getCfg('header/canvas_cart') == 0) echo 'minicart-wrapper-detail';?>">
        <div class="action showcart_mobile <?=isset($settingData->{'_customize-radio-cart_mobile_icon_style'}) && $settingData->{'_customize-radio-cart_mobile_icon_style'} ? $settingData->{'_customize-radio-cart_mobile_icon_style'} : '';?>" data-bind="scope: 'minicart_content'">
            <?php if(isset($settingData->{'_customize_header_cart_mobile_title'}) && $settingData->{'_customize_header_cart_mobile_title'} == '1'):?>
                <span class="minicart-title">My Cart</span>
            <?php endif?>
            <a href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>" class="icon minicart minicart-mobile">
                <?php if(isset($settingData->cart_mobileicon->value) && $settingData->cart_mobileicon->value):?>
                    <img src="<?=$headerBuilderHelper->getMediaUrl().'cleversoft/headerbuilder/'.$settingData->cart_mobileicon->value?>" id="customize-control_header_cart_mobileicon_image" height="30" width="30" class="small-image-preview v-middle" >
                <?php else:?>
                    <i class="cs-font <?=isset($settingData->{'_customize-radio-cart_mobile_icon'}) && $settingData->{'_customize-radio-cart_mobile_icon'} ? $settingData->{'_customize-radio-cart_mobile_icon'} : 'clever-icon-cart-14';?>"></i>
                <?php endif?>
                
                <!-- ko if: getCartParam('summary_count') -->
                <span class="counter qty empty"
                      data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                    <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><?=$countItem?><!-- /ko --></span>
                    <span class="counter-label">
                    <!-- ko if: getCartParam('summary_count') -->
                        <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                        <!-- ko i18n: 'items' --><!-- /ko -->
                    <!-- /ko -->
                    </span>
                </span>
                <!-- /ko -->
            </a>
            <?php if(isset($settingData->{'_customize_header_cart_mobile_total'}) && $settingData->{'_customize_header_cart_mobile_total'} == '1'):?>
            <div class="subtotal-minicart" data-bind="html : getCartParam('subtotal')"><span class="price"><?=$subtotal?></div>
        <?php endif?>
        </div>
        <?php if ($block->getIsNeedToDisplaySideBar()): ?>
            <div class="block block-minicart-mobile <?php if( $_matoHelper->getCfg('header/canvas_cart') == 1) echo 'minicart-detail'; else echo 'minicart-detail-default';?> empty"
                 data-role="dropdownDialog"
                 data-mage-init='{"dropdownDialog":{
                    "appendTo":"[data-block=minicart-mobile]",
                    "triggerTarget":".showcart_mobile",
                    "timeout": "2000",
                    "closeOnMouseLeave": false,
                    "closeOnEscape": true,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":[]}}'>
                <div id="minicart-content-wrapper-mobile" data-bind="scope: 'minicart_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
                <?php echo $block->getChildHtml('minicart.addons'); ?>
            </div>
        <?php endif ?>
        <script>
            window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
        </script>
        <script type="text/x-magento-init">
        {
            "[data-block='minicart-mobile']": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            },
            "*": {
                "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
            }
        }
        </script>
    </div>
<?php else:?>
    <div data-block="minicart-mobile" class="minicart-wrapper">
        <?php if(isset($settingData->{'_customize_header_cart_mobile_title'}) && $settingData->{'_customize_header_cart_mobile_title'} == '1'):?>
            <span class="minicart-title">My Cart</span>
        <?php endif?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>" class="icon action showcart_mobile minicart minicart-mobile <?=isset($settingData->{'_customize-radio-cart_mobile_icon_style'}) && $settingData->{'_customize-radio-cart_mobile_icon_style'} ? $settingData->{'_customize-radio-cart_mobile_icon_style'} : '';?>" data-bind="scope: 'minicart_content'">
            <?php if(isset($settingData->cart_mobileicon->value) && $settingData->cart_mobileicon->value):?>
                <img src="<?=$headerBuilderHelper->getMediaUrl().'cleversoft/headerbuilder/'.$settingData->cart_mobileicon->value?>" id="customize-control_header_cart_mobileicon_image" height="30" width="30" class="small-image-preview v-middle" >
            <?php else:?>
                <i class="cs-font <?=isset($settingData->{'_customize-radio-cart_mobile_icon'}) && $settingData->{'_customize-radio-cart_mobile_icon'} ? $settingData->{'_customize-radio-cart_mobile_icon'} : 'clever-icon-cart-14';?>"></i>
            <?php endif?>
            
            <!-- ko if: getCartParam('summary_count') -->
            <span class="counter qty empty"
                  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><?=$countItem?><!-- /ko --></span>
                <span class="counter-label">
                <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                    <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->
                </span>
            </span>
            <!-- /ko -->
        </a>
        <?php if(isset($settingData->{'_customize_header_cart_mobile_total'}) && $settingData->{'_customize_header_cart_mobile_total'} == '1'):?>
            <div class="subtotal-minicart" data-bind="html : getCartParam('subtotal')"><span class="price"><?=$subtotal?></div>
        <?php endif?>
    </div>
<?php endif;?>
